## 1. Answer the questions from the introduction

1.1. Что такое метод «leave-one-out»? Укажите его ограничения и сильные стороны.

### Leave-One-Out (LOO) - ### 
это предельный случай k-fold кросс-валидации, где количество блоков равно размеру датасета. Алгоритм по очереди берет каждый объект в качестве тестового набора, а все остальные данные использует для обучения.
Алгоритм работы: 
1. Выбирается 1 объект для тестирования
2. Модель обучается на всех оставшихся n-1 объектах
3. Модель делает предсказаение для исключенного объекта и фиксирует ошибку
4. Процедура повторяется n раз (n - общее число объектов в выборке), пока каждый объект не побывает в роли тестового
5. Вычисляется средняя ошибка по всем n итерациям

Преимущества:
- Максимальное использование данных, т.е. в каждом цикле модель обучается почти на 100% доступных данных
- Отсутствие случайности - исключается фактор удачного или неудачного разбиения, т.е. результат всегда детерминирован
- Идеально для микро-датасетов

Недостатки:
- Колоссальная вычислительная сложность, если датасет большой, то модели придется много обучаться, что требует много времени и ресурсов
- Высокая дисперсия - т.к. тренировочные выборки на разных итерациях почти идентичны (n-1), оценки предсказаний могут сильно колебаться от объекта к объекту.

1.2. Как работают алгоритмы поиска по сетке, случайного поиска по сетке и байесовской оптимизации?

- ### Поиск по сетке (Grid Search) - ### 
принимает на вход вручную заданные диапазоны гиперпараметров и полностью перебирает все комбинации, чтобы найти лучшую. 
Плюсы: гарантирует нахождение идеального оптимума в пределах заданной сетки.
Минусы: очень медленный.

- ### Случайный поиск (Random Search) - ### 
пробует случайные комбинации гиперпараметров, чтобы найти наилучшее решение, вместо конкретных значений для каждого гиперпараметра задается статистическое распределение (например равномерное или логарифмическое). Алгоритм выбират случайные комбинации и обучает модель заданное количество раз.
Плюсы: быстрее и экономнее вычислительно.
Минусы: может пропустить оптимальную точку.

- ### Байсовская оптимизация (Bayesian Optimization) - ### 
вероятностный подход, который "учится" на предыдущих попытках. Строит суррогатную вероятностную модель, которая отображает зависимость между гиперпараметрами и результатом. Использует функцию приобретения, чтобы решить, куда двигаться дальше: изучать неизвестные области или детально исследовать зоны вокрег уже показавших результат параметров. Оценивает функцию на реальной модели, обновляет суррогатную модель и повторяет цикл.
Плюсы: высокая эффективность, находит оптимальные параметры за минимальное количество итераций.
Минусы: алгоритм сложнее в настройки, расчет следующей точки требует дополнительного времени.

1.3. Классификация методов отбора признаков (Feature selection). Объясните, как работают коэффициенты Пирсона и хи-квадрат. Объясните, как работает метод Lasso. Объясните, что такое значимость перестановок. Ознакомьтесь с методом SHAP.

### Feature selection - ###
процесс выбора наиболее значимых переменных (признаков) для обучения модели. 

Основные методы:

- Фильтры (Filter) - оценивают признаки на основе статистических взаимосвязей с целевой переменной (напр: коэффициент корреляции Пирсона, Хи-квадрат)

Коэффициент Пирсона - показывает степень линейной связи между двумя количественными признаками или между признаком и числовой целевой переменной. Значение изменяется от -1 до +1, которые указывают на сильную прямую или обратную свзяь. Значение 0 означает полное отсутсвие линейной зависимости. Признаки с высоким коэффициентом корреляции с целевой переменной отбираются, а избыточные (сильно коррелирующие между собой) - удаляются.

Хи-квадрат - статистический тест, который оценивает независимость между двумя категориальными переменными. Тест сравнивает фактические (наблюдаемые) частоты категорий с теоретическими (ожидаемыми), если бы признаки были абсолютно независимы. Чем выше знаечние х2, тем больше зависимость между признаком целевой переменной. Признаи с низким х2 (и высоким p-value) отбрасываются, тк они неинформативны для классификации.

- Обертки (Wrapper) - ищут оптимальную комбинацию признаков путем многократного обучения и оценки качества самой модели.

- Встроенные (Embedded) - объединяют свойства двух предыдщих методов. Выбор признаков происходит непосредственно в процессе обучения самой модели (напр: Lasso, Ridge).

Lasso (L1-регуляризация) - метод линейной регрессии, к функции потерь которого добавляется штраф за абсолютную величину весов параметров. Из за ромбовидной формы ограничений в L1-регуляризации, веса наименее важных признаков сжимаются ровно до нуля. 

### Значимость перестановок (Permutation Feature Importance) - ###
способ оценки того, насколько сильно обученная модель зависит от конкретного признака. Рассчитвается после обучения модели.

### Метод SHAP (SHapley Additive exPlanations) - ###
объясняет предсказания любых моделй машинного обучения (черных ящиков). Рассматривает каждый признак в объекте как "игрока" в игре, где выигрыш - предсказание модели.

## 2. Introduction

In [1]:
import pandas as pd
import numpy as np
import sklearn
import lightgbm
import scipy
import statsmodels
import seaborn as sns
import warnings
import time
import shap
import optuna
from collections import Counter, defaultdict
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split, KFold, StratifiedKFold, GroupKFold, TimeSeriesSplit, cross_val_score, cross_validate, GridSearchCV, RandomizedSearchCV
from sklearn.linear_model import ElasticNet
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from itertools import combinations
from sklearn.linear_model import Lasso
from sklearn.inspection import permutation_importance
warnings.filterwarnings('ignore')

In [2]:
df_train = pd.read_json('./data/train.json')

Предобработка df_train как в предыдщуем задании

In [3]:
values = df_train['price'].values
lower = np.percentile(values, 1)
upper = np.percentile(values, 99)
mask = (values >= lower) & (values <= upper)
df_train = df_train[mask]
df_train['price'].describe()

count    48379.000000
mean      3538.636888
std       1597.663167
min       1475.000000
25%       2500.000000
50%       3150.000000
75%       4065.000000
max      13000.000000
Name: price, dtype: float64

In [4]:
le = LabelEncoder()
df_train['interest_level'] = le.fit_transform(df_train['interest_level'])
df_train.head(5)

,bathrooms,bedrooms,building_id,created,description,display_address,features,latitude,listing_id,longitude,manager_id,photos,price,street_address,interest_level
4,1.0,1,8579a0b0d54db803821a35a4a615e97a,2016-06-16 05:55:27,Spacious 1 Bedroom 1 Bathroom in Williamsburg!...,145 Borinquen Place,"[Dining Room, Pre-War, Laundry in Building, Di...",40.7108,7170325,-73.9539,a10db4590843d78c784171a107bdacb4,[https://photos.renthop.com/2/7170325_3bb5ac84...,2400,145 Borinquen Place,2
6,1.0,2,b8e75fc949a6cd8225b455648a951712,2016-06-01 05:44:33,BRAND NEW GUT RENOVATED TRUE 2 BEDROOMFind you...,East 44th,"[Doorman, Elevator, Laundry in Building, Dishw...",40.7513,7092344,-73.9722,955db33477af4f40004820b4aed804a0,[https://photos.renthop.com/2/7092344_7663c19a...,3800,230 East 44th,1
9,1.0,2,cd759a988b8f23924b5a2058d5ab2b49,2016-06-14 15:19:59,**FLEX 2 BEDROOM WITH FULL PRESSURIZED WALL**L...,East 56th Street,"[Doorman, Elevator, Laundry in Building, Laund...",40.7575,7158677,-73.9625,c8b10a317b766204f08e613cef4ce7a0,[https://photos.renthop.com/2/7158677_c897a134...,3495,405 East 56th Street,2
10,1.5,3,53a5b119ba8f7b61d4e010512e0dfc85,2016-06-24 07:54:24,A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...,Metropolitan Avenue,[],40.7145,7211212,-73.9425,5ba989232d0489da1b5f2c45f6688adc,[https://photos.renthop.com/2/7211212_1ed4542e...,3000,792 Metropolitan Avenue,2
15,1.0,0,bfb9405149bfff42a92980b594c28234,2016-06-28 03:50:23,Over-sized Studio w abundant closets. Availabl...,East 34th Street,"[Doorman, Elevator, Fitness Center, Laundry in...",40.7439,7225292,-73.9743,2c3b41f588fbb5234d8a1e885a436cfa,[https://photos.renthop.com/2/7225292_901f1984...,2795,340 East 34th Street,1

In [5]:
df_train['features'] = df_train['features'].apply(
    lambda x: str(x).translate(str.maketrans('', '', '[]\'" '))
)
df_train['features'].head()

4     DiningRoom,Pre-War,LaundryinBuilding,Dishwashe...
6     Doorman,Elevator,LaundryinBuilding,Dishwasher,...
9     Doorman,Elevator,LaundryinBuilding,LaundryinUn...
10
15     Doorman,Elevator,FitnessCenter,LaundryinBuilding
Name: features, dtype: str

In [6]:
all_features = []

for _, row in df_train.iterrows():
    val = row['features']
    if pd.notna(val) and val != '':
        all_features.extend(val.split(','))

feature_counts = Counter(all_features)
top_20_features = [feature for feature, count in feature_counts.most_common(20)]

feature_sets = df_train['features'].apply(
    lambda x: set(x.split(',')) if pd.notna(x) and x != '' else set()
)

new_df = pd.DataFrame()
for feature in top_20_features:
    new_df[feature] = feature_sets.apply(lambda x: 1 if feature in x else 0)

new_df.head(5)

,Elevator,HardwoodFloors,CatsAllowed,DogsAllowed,Doorman,Dishwasher,NoFee,LaundryinBuilding,FitnessCenter,Pre-War,LaundryinUnit,RoofDeck,OutdoorSpace,DiningRoom,HighSpeedInternet,Balcony,SwimmingPool,LaundryInBuilding,NewConstruction,Terrace
4,0,1,1,1,0,1,0,1,0,1,0,0,0,1,0,0,0,0,0,0
6,1,1,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0
9,1,1,0,0,1,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,1,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0

In [7]:
df = pd.concat((df_train, new_df), axis=1)
df.head(5)

,bathrooms,bedrooms,building_id,created,description,display_address,features,latitude,listing_id,longitude,...,LaundryinUnit,RoofDeck,OutdoorSpace,DiningRoom,HighSpeedInternet,Balcony,SwimmingPool,LaundryInBuilding,NewConstruction,Terrace
4,1.0,1,8579a0b0d54db803821a35a4a615e97a,2016-06-16 05:55:27,Spacious 1 Bedroom 1 Bathroom in Williamsburg!...,145 Borinquen Place,"DiningRoom,Pre-War,LaundryinBuilding,Dishwashe...",40.7108,7170325,-73.9539,...,0,0,0,1,0,0,0,0,0,0
6,1.0,2,b8e75fc949a6cd8225b455648a951712,2016-06-01 05:44:33,BRAND NEW GUT RENOVATED TRUE 2 BEDROOMFind you...,East 44th,"Doorman,Elevator,LaundryinBuilding,Dishwasher,...",40.7513,7092344,-73.9722,...,0,0,0,0,0,0,0,0,0,0
9,1.0,2,cd759a988b8f23924b5a2058d5ab2b49,2016-06-14 15:19:59,**FLEX 2 BEDROOM WITH FULL PRESSURIZED WALL**L...,East 56th Street,"Doorman,Elevator,LaundryinBuilding,LaundryinUn...",40.7575,7158677,-73.9625,...,1,0,0,0,0,0,0,0,0,0
10,1.5,3,53a5b119ba8f7b61d4e010512e0dfc85,2016-06-24 07:54:24,A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...,Metropolitan Avenue,,40.7145,7211212,-73.9425,...,0,0,0,0,0,0,0,0,0,0
15,1.0,0,bfb9405149bfff42a92980b594c28234,2016-06-28 03:50:23,Over-sized Studio w abundant closets. Availabl...,East 34th Street,"Doorman,Elevator,FitnessCenter,LaundryinBuilding",40.7439,7225292,-73.9743,...,0,0,0,0,0,0,0,0,0,0

In [8]:
df.info()

<class 'pandas.DataFrame'>
Index: 48379 entries, 4 to 124009
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   bathrooms          48379 non-null  float64
 1   bedrooms           48379 non-null  int64
 2   building_id        48379 non-null  str
 3   created            48379 non-null  str
 4   description        48379 non-null  str
 5   display_address    48379 non-null  str
 6   features           48379 non-null  str
 7   latitude           48379 non-null  float64
 8   listing_id         48379 non-null  int64
 9   longitude          48379 non-null  float64
 10  manager_id         48379 non-null  str
 11  photos             48379 non-null  object
 12  price              48379 non-null  int64
 13  street_address     48379 non-null  str
 14  interest_level     48379 non-null  int64
 15  Elevator           48379 non-null  int64
 16  HardwoodFloors     48379 non-null  int64
 17  CatsAllowed        48379 non-null  int64
 18  DogsAllowed        48379 non-null  int64
 19  Doorman            48379 non-null  int64
 20  Dishwasher         48379 non-null  int64
 21  NoFee              48379 non-null  int64
 22  LaundryinBuilding  48379 non-null  int64
 23  FitnessCenter      48379 non-null  int64
 24  Pre-War            48379 non-null  int64
 25  LaundryinUnit      48379 non-null  int64
 26  RoofDeck           48379 non-null  int64
 27  OutdoorSpace       48379 non-null  int64
 28  DiningRoom         48379 non-null  int64
 29  HighSpeedInternet  48379 non-null  int64
 30  Balcony            48379 non-null  int64
 31  SwimmingPool       48379 non-null  int64
 32  LaundryInBuilding  48379 non-null  int64
 33  NewConstruction    48379 non-null  int64
 34  Terrace            48379 non-null  int64
dtypes: float64(3), int64(24), object(1), str(7)
memory usage: 13.3+ MB

In [9]:
df['created'] = pd.to_datetime(df['created'])
print(f"Минимальная дата: {df['created'].min()}")
print(f"Максимальная дата: {df['created'].max()}")
print(f"Количество уникальных дат: {df['created'].nunique()}")
print(f"Всего записей: {len(df)}")

Минимальная дата: 2016-04-01 22:12:41
Максимальная дата: 2016-06-29 21:41:47
Количество уникальных дат: 47719
Всего записей: 48379

## 3. Implement the next methods:

In [10]:
X = df.drop('price', axis=1)
y = df['price']

In [11]:
class DataSplitter:
    def __init__(self, random_state=42):
        self.random_state = random_state
        np.random.seed(random_state)

    def train_test_random_split(self, X, y, test_size=0.2):
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=self.random_state)

        print(f"Обучающая выборка: {X_train.shape[0]} объектов")
        print(f"Тестовая выборка: {X_test.shape[0]} объектов")
        
        return X_train, X_test, y_train, y_test
    
    def train_valid_test_random_split(self, X, y, validation_size=0.15, test_size=0.15):
        X_temp, X_test, y_temp, y_test = train_test_split(
            X, y,
            test_size=test_size,
            random_state=self.random_state
        )

        relative_valid_size = validation_size / (1 - test_size)
        
        X_train, X_valid, y_train, y_valid = train_test_split(
            X_temp, y_temp,
            test_size=relative_valid_size,
            random_state=self.random_state
        )

        print(f"Обучающая выборка: {X_train.shape[0]} объектов")
        print(f"Валидационная выборка: {X_valid.shape[0]} объектов")
        print(f"Тестовая выборка: {X_test.shape[0]} объектов")
        
        return X_train, X_valid, X_test, y_train, y_valid, y_test

    def train_test_date_split(self, X, y, date_split):
        split_date = pd.to_datetime(date_split)

        train_mask = X['created'] < split_date
        test_mask = X['created'] >= split_date

        X_train = X[train_mask]
        X_test = X[test_mask]
        y_train = y[train_mask]
        y_test = y[test_mask]
        
        print(f"Дата разделения: {split_date.date()}")
        print(f"Обучающая выборка: {X_train.shape[0]} объектов (до {split_date.date()})")
        print(f"Тестовая выборка: {X_test.shape[0]} объектов (с {split_date.date()})")
        
        return X_train, X_test, y_train, y_test
    

    def train_valid_test_date_split(self, X, y, validation_date, test_date):
        valid_date = pd.to_datetime(validation_date)
        test_date = pd.to_datetime(test_date)

        train_mask = X['created'] < valid_date
        valid_mask = (X['created'] >= valid_date) & (X['created'] < test_date)
        test_mask = X['created'] >= test_date
        
        X_train = X[train_mask]
        X_valid = X[valid_mask]
        X_test = X[test_mask]
        
        y_train = y[train_mask]
        y_valid = y[valid_mask]
        y_test = y[test_mask]

        print(f"Обучающая выборка: {X_train.shape[0]} объектов (до {valid_date.date()})")
        print(f"Валидационная выборка: {X_valid.shape[0]} объектов ({valid_date.date()} - {test_date.date()})")
        print(f"Тестовая выборка: {X_test.shape[0]} объектов (с {test_date.date()})")
        
        return X_train, X_valid, X_test, y_train, y_valid, y_test

In [12]:
splitter = DataSplitter(random_state=42)

print("Метод 1: Случайное разделение на 2 части (train/test)")
X_train, X_test, y_train, y_test = splitter.train_test_random_split(X, y, test_size=0.2)
print()

print("Метод 2: Случайное разделение на 3 части (train/valid/test)")
X_train, X_valid, X_test, y_train, y_valid, y_test = splitter.train_valid_test_random_split(X, y, validation_size=0.15, test_size=0.15)
print()

print("Метод 3: Разделение по дате на 2 части")
X_train, X_test, y_train, y_test = splitter.train_test_date_split(X, y, date_split='2016-06-01')
print()

print("Метод 4: Разделение по дате на 3 части")
X_train, X_valid, X_test, y_train, y_valid, y_test = splitter.train_valid_test_date_split(X, y, validation_date='2016-04-30', test_date='2016-06-01')
print()

Метод 1: Случайное разделение на 2 части (train/test)
Обучающая выборка: 38703 объектов
Тестовая выборка: 9676 объектов

Метод 2: Случайное разделение на 3 части (train/valid/test)
Обучающая выборка: 33865 объектов
Валидационная выборка: 7257 объектов
Тестовая выборка: 7257 объектов

Метод 3: Разделение по дате на 2 части
Дата разделения: 2016-06-01
Обучающая выборка: 31576 объектов (до 2016-06-01)
Тестовая выборка: 16803 объектов (с 2016-06-01)

Метод 4: Разделение по дате на 3 части
Обучающая выборка: 15606 объектов (до 2016-04-30)
Валидационная выборка: 15970 объектов (2016-04-30 - 2016-06-01)
Тестовая выборка: 16803 объектов (с 2016-06-01)

## 4. Implement the next cross-validation methods:

In [13]:
class CrossValidator:
    def __init__(self, random_state=42):
        self.random_state = random_state
        np.random.seed(random_state)

    def kfold_split(self, X, y, k=5, shuffle=True):
        n_samples = len(X)
        indices = np.arange(n_samples)
        if shuffle:
            np.random.seed(self.random_state)
            np.random.shuffle(indices)

        fold_sizes = [n_samples // k] * k
        remainder = n_samples % k
        for i in range(remainder):
            fold_sizes[i] += 1
        
        folds = []
        current = 0
        for size in fold_sizes:
            folds.append(indices[current:current + size])
            current += size

        cv_splits = []
        for i in range(k):
            test_indices = folds[i]
            train_indices = np.concatenate([folds[j] for j in range(k) if j != i])
            cv_splits.append((train_indices, test_indices))
            
            print(f"Fold {i+1}: Train {len(train_indices)} объектов Test {len(test_indices)} объектов")
        
        return cv_splits
    
    def group_kfold_split(self, X, y, group_field=None, k=5):
        if isinstance(X, pd.DataFrame):
            if group_field is None:
                groups = np.arange(len(X))
                print("group_field не указан: каждый объект считается отдельной группой")
            elif isinstance(group_field, str):
                groups = X[group_field].values
                print(f"Группировка по полю: '{group_field}'")
            elif isinstance(group_field, list):
                groups = X[group_field].astype(str).agg('_'.join, axis=1).values
                print(f"Группировка по полям: {group_field}")
            else:
                raise ValueError("group_field должен быть str, list или None")
    
        unique_groups = np.unique(groups)
        n_groups = len(unique_groups)

        np.random.seed(self.random_state)
        shuffled_groups = np.random.permutation(unique_groups)

        group_folds = np.array_split(shuffled_groups, k)

        group_to_indices = defaultdict(list)
        for idx, group in enumerate(groups):
            group_to_indices[group].append(idx)
    
        cv_splits = []
        for i in range(k):
            test_groups = group_folds[i]
            train_groups = np.concatenate([group_folds[j] for j in range(k) if j != i])
        
            test_indices = []
            for group in test_groups:
                test_indices.extend(group_to_indices[group])
        
            train_indices = []
            for group in train_groups:
                train_indices.extend(group_to_indices[group])
        
            test_indices = np.array(test_indices)
            train_indices = np.array(train_indices)
        
            cv_splits.append((train_indices, test_indices))

            print(f"Fold {i+1}: Train {len(train_indices)} объектов ({len(train_groups)} групп) Test {len(test_indices)} объектов ({len(test_groups)} групп)")
            
        return cv_splits
    
    def stratified_kfold_split(self, X, y, stratify_field=None, k=5, shuffle=True):    
        if stratify_field is not None:
            if isinstance(stratify_field, str):
                stratify_values = X[stratify_field].values
                print(f"Стратификация по полю: '{stratify_field}'")
            elif isinstance(stratify_field, list):
                stratify_values = X[stratify_field].astype(str).agg('_'.join, axis=1).values
                print(f"Стратификация по полям: {stratify_field}")
            else:
                raise ValueError("stratify_field должен быть str или list")
        else:
            if y is None:
                raise ValueError("Необходимо указать либо y, либо stratify_field")
            stratify_values = np.array(y)
            print("Стратификация по целевой переменной y")
            
        stratify_values = np.array(stratify_values)
        n_samples = len(X)
        unique_strata = np.unique(stratify_values)
        
        test_folds = np.empty(n_samples, dtype=int)
        test_folds.fill(-1)
        
        strata_counts = {}
        for strata in unique_strata:
            strata_counts[strata] = np.sum(stratify_values == strata)
        
        for strata in unique_strata:
            strata_indices = np.where(stratify_values == strata)[0]
            if shuffle:
                np.random.seed(self.random_state)
                np.random.shuffle(strata_indices)
            n_strata = len(strata_indices)
            
            fold_order = np.arange(k)
            if shuffle:
                np.random.seed(self.random_state)
                np.random.shuffle(fold_order)

            for i, idx in enumerate(strata_indices):
                fold_idx = fold_order[i % k]
                test_folds[idx] = fold_idx

        folds = []
        for i in range(k):
            fold_indices = np.where(test_folds == i)[0]
            folds.append(fold_indices)

        cv_splits = []
        for i in range(k):
            test_indices = folds[i]
            train_indices = np.concatenate([folds[j] for j in range(k) if j != i])
            cv_splits.append((train_indices, test_indices))

            
            print(f"Fold {i+1}: Train {len(train_indices)} объектов Test {len(test_indices)} объектов")

            train_dist = X.iloc[train_indices]['bedrooms'].value_counts(normalize=True).sort_index()
            test_dist = X.iloc[test_indices]['bedrooms'].value_counts(normalize=True).sort_index()
            original_dist = X['bedrooms'].value_counts(normalize=True).sort_index()

            print("Распределение bedrooms:")
            for bedrooms_count in original_dist.index:
                print(f"{bedrooms_count} bedrooms: "
                      f"Все данные={original_dist[bedrooms_count]:.1%}, "
                      f"Train={train_dist.get(bedrooms_count, 0):.1%}, "
                      f"Test={test_dist.get(bedrooms_count, 0):.1%}")

        return cv_splits
    
    def time_series_split(self, X, y=None, date_field=None, k=5):
        if k > len(X):
            raise ValueError
        
        x_sorted = X.sort_values(by=date_field).reset_index(drop=True)
        n_samples = len(x_sorted)
        test_size = n_samples // (k + 1)
        
        if test_size == 0:
            raise ValueError
        
        cv_splits = []
        
        for i in range(1, k + 1):
            train_indices = np.arange(i * test_size)
            test_indices = np.arange(i * test_size, (i + 1) * test_size)
            
            cv_splits.append((train_indices, test_indices))
                
            print(f"Fold {i+1}: Train {len(train_indices)} объектов Test {len(test_indices)} объектов")
        
        return cv_splits

## 5. Cross-validation comparison

In [14]:
cv = CrossValidator(random_state=42)

print("МЕТОД 1: K-Fold кросс-валидация (k=5)")
kfold_splits = cv.kfold_split(X, y, k=5, shuffle=True)

МЕТОД 1: K-Fold кросс-валидация (k=5)
Fold 1: Train 38703 объектов Test 9676 объектов
Fold 2: Train 38703 объектов Test 9676 объектов
Fold 3: Train 38703 объектов Test 9676 объектов
Fold 4: Train 38703 объектов Test 9676 объектов
Fold 5: Train 38704 объектов Test 9675 объектов

In [15]:
print("МЕТОД 2: Групповая K-Fold (k=5)")
group_splits = cv.group_kfold_split(X, y, group_field='bedrooms', k=5)

МЕТОД 2: Групповая K-Fold (k=5)
Группировка по полю: 'bedrooms'
Fold 1: Train 32838 объектов (7 групп) Test 15541 объектов (2 групп)
Fold 2: Train 38972 объектов (7 групп) Test 9407 объектов (2 групп)
Fold 3: Train 33831 объектов (7 групп) Test 14548 объектов (2 групп)
Fold 4: Train 39540 объектов (7 групп) Test 8839 объектов (2 групп)
Fold 5: Train 48335 объектов (8 групп) Test 44 объектов (1 групп)

In [16]:
print("МЕТОД 3: Стратифицированная K-Fold (k=5)")
stratified_splits = cv.stratified_kfold_split(X, y, stratify_field='bedrooms', shuffle=True)

МЕТОД 3: Стратифицированная K-Fold (k=5)
Стратификация по полю: 'bedrooms'
Fold 1: Train 38705 объектов Test 9674 объектов
Распределение bedrooms:
0 bedrooms: Все данные=19.0%, Train=19.0%, Test=19.0%
1 bedrooms: Все данные=32.1%, Train=32.1%, Test=32.1%
2 bedrooms: Все данные=30.1%, Train=30.1%, Test=30.1%
3 bedrooms: Все данные=14.6%, Train=14.6%, Test=14.6%
4 bedrooms: Все данные=3.7%, Train=3.7%, Test=3.7%
5 bedrooms: Все данные=0.4%, Train=0.4%, Test=0.4%
6 bedrooms: Все данные=0.1%, Train=0.1%, Test=0.1%
7 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%
8 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%
Fold 2: Train 38698 объектов Test 9681 объектов
Распределение bedrooms:
0 bedrooms: Все данные=19.0%, Train=19.0%, Test=19.0%
1 bedrooms: Все данные=32.1%, Train=32.1%, Test=32.1%
2 bedrooms: Все данные=30.1%, Train=30.1%, Test=30.1%
3 bedrooms: Все данные=14.6%, Train=14.6%, Test=14.6%
4 bedrooms: Все данные=3.7%, Train=3.7%, Test=3.7%
5 bedrooms: Все данные=0.4%, Train=0.4%, Test=0.4%
6 bedrooms: Все данные=0.1%, Train=0.1%, Test=0.1%
7 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%
8 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%
Fold 3: Train 38704 объектов Test 9675 объектов
Распределение bedrooms:
0 bedrooms: Все данные=19.0%, Train=19.0%, Test=19.0%
1 bedrooms: Все данные=32.1%, Train=32.1%, Test=32.1%
2 bedrooms: Все данные=30.1%, Train=30.1%, Test=30.1%
3 bedrooms: Все данные=14.6%, Train=14.6%, Test=14.6%
4 bedrooms: Все данные=3.7%, Train=3.7%, Test=3.7%
5 bedrooms: Все данные=0.4%, Train=0.4%, Test=0.4%
6 bedrooms: Все данные=0.1%, Train=0.1%, Test=0.1%
7 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%
8 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%
Fold 4: Train 38706 объектов Test 9673 объектов
Распределение bedrooms:
0 bedrooms: Все данные=19.0%, Train=19.0%, Test=19.0%
1 bedrooms: Все данные=32.1%, Train=32.1%, Test=32.1%
2 bedrooms: Все данные=30.1%, Train=30.1%, Test=30.1%
3 bedrooms: Все данные=14.6%, Train=14.6%, Test=14.6%
4 bedrooms: Все данные=3.7%, Train=3.7%, Test=3.7%
5 bedrooms: Все данные=0.4%, Train=0.4%, Test=0.4%
6 bedrooms: Все данные=0.1%, Train=0.1%, Test=0.1%
7 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%
8 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%
Fold 5: Train 38703 объектов Test 9676 объектов
Распределение bedrooms:
0 bedrooms: Все данные=19.0%, Train=19.0%, Test=19.0%
1 bedrooms: Все данные=32.1%, Train=32.1%, Test=32.1%
2 bedrooms: Все данные=30.1%, Train=30.1%, Test=30.1%
3 bedrooms: Все данные=14.6%, Train=14.6%, Test=14.6%
4 bedrooms: Все данные=3.7%, Train=3.7%, Test=3.7%
5 bedrooms: Все данные=0.4%, Train=0.4%, Test=0.4%
6 bedrooms: Все данные=0.1%, Train=0.1%, Test=0.1%
7 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%
8 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%

In [17]:
print("МЕТОД 4: Временная K-Fold (k=5)")
time_splits = cv.time_series_split(X, y, date_field='created', k=5)

МЕТОД 4: Временная K-Fold (k=5)
Fold 2: Train 8063 объектов Test 8063 объектов
Fold 3: Train 16126 объектов Test 8063 объектов
Fold 4: Train 24189 объектов Test 8063 объектов
Fold 5: Train 32252 объектов Test 8063 объектов
Fold 6: Train 40315 объектов Test 8063 объектов

### Реализация методов из библиотеки sklearn

In [18]:
print("МЕТОД 1 sklearn: K-Fold кросс-валидация (k=5)")
kf = KFold(n_splits=5, shuffle=True, random_state=42)
for fold, (train_idx, test_idx) in enumerate(kf.split(X, y), 1):
    print(f"Fold {fold}: Train {len(train_idx)} Test {len(test_idx)}")

МЕТОД 1 sklearn: K-Fold кросс-валидация (k=5)
Fold 1: Train 38703 Test 9676
Fold 2: Train 38703 Test 9676
Fold 3: Train 38703 Test 9676
Fold 4: Train 38703 Test 9676
Fold 5: Train 38704 Test 9675

In [19]:
print("МЕТОД 2 sklearn: Групповая K-Fold (k=5)")
gkf = GroupKFold(n_splits=5)
groups = X['bedrooms'].values
for fold, (train_idx, test_idx) in enumerate(gkf.split(X, groups=groups), 1):
    train_groups = set(groups[train_idx])
    test_groups = set(groups[test_idx])
    print(f"Fold {fold}: Train {len(train_idx)} объектов ({len(train_groups)} групп) Test {len(test_idx)} объектов ({len(test_groups)} групп)")
print()

МЕТОД 2 sklearn: Групповая K-Fold (k=5)
Fold 1: Train 32839 объектов (8 групп) Test 15540 объектов (1 групп)
Fold 2: Train 33833 объектов (8 групп) Test 14546 объектов (1 групп)
Fold 3: Train 39178 объектов (8 групп) Test 9201 объектов (1 групп)
Fold 4: Train 41318 объектов (8 групп) Test 7061 объектов (1 групп)
Fold 5: Train 46348 объектов (4 групп) Test 2031 объектов (5 групп)

In [20]:
warnings.filterwarnings('ignore', category=UserWarning, module='sklearn.model_selection')

print("МЕТОД 3 sklearn: Стратифицированная K-Fold (k=5)")
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
stratify_values = X['bedrooms'].values
for fold, (train_idx, test_idx) in enumerate(skf.split(X, y=stratify_values), 1):
        train_strata = stratify_values[train_idx]
        test_strata = stratify_values[test_idx]
        print(f"Fold {fold}: Train {len(train_idx)} объектов Test {len(test_idx)} объектов")

МЕТОД 3 sklearn: Стратифицированная K-Fold (k=5)
Fold 1: Train 38703 объектов Test 9676 объектов
Fold 2: Train 38703 объектов Test 9676 объектов
Fold 3: Train 38703 объектов Test 9676 объектов
Fold 4: Train 38703 объектов Test 9676 объектов
Fold 5: Train 38704 объектов Test 9675 объектов

In [21]:
print("МЕТОД 4 sklearn: Временная K-Fold (k=5)")
tscv = TimeSeriesSplit(n_splits=5)
for fold, (train_idx, test_idx) in enumerate(tscv.split(X), 1):
    train_dates = df.iloc[train_idx]['created']
    test_dates = df.iloc[test_idx]['created']
    print(f"Fold {fold}: Train {len(train_idx)} объектов Test {len(test_idx)} объектов")

МЕТОД 4 sklearn: Временная K-Fold (k=5)
Fold 1: Train 8064 объектов Test 8063 объектов
Fold 2: Train 16127 объектов Test 8063 объектов
Fold 3: Train 24190 объектов Test 8063 объектов
Fold 4: Train 32253 объектов Test 8063 объектов
Fold 5: Train 40316 объектов Test 8063 объектов

### Сравниваем распределения признаков на train части данных

In [22]:
class CrossValidatorComparison:

    def __init__(self, X, y, random_state=42):
        self.X = X
        self.y = y
        self.random_state = random_state
        self.cv = CrossValidator(random_state=random_state)
        self.feature_columns = self._get_numeric_columns()
        self.timings = {}

    def _get_numeric_columns(self):
        numeric_cols = self.X.select_dtypes(include=[np.number]).columns.tolist()
        if 'price' in numeric_cols:
            numeric_cols.remove('price')
        return numeric_cols[:3]
    
    def split_data(self, val_size=0.2, test_size=0.2):
        """
        Разделение данных на train, validation, test
        """
        X_train, X_temp, y_train, y_temp = train_test_split(
            self.X, self.y, 
            test_size=(val_size + test_size), 
            random_state=self.random_state
        )
        
        X_val, X_test, y_val, y_test = train_test_split(
            X_temp, y_temp, 
            test_size=test_size / (val_size + test_size), 
            random_state=self.random_state
        )
        
        self.X_train = X_train.reset_index(drop=True)
        self.X_val = X_val.reset_index(drop=True)
        self.X_test = X_test.reset_index(drop=True)
        self.y_train = y_train.reset_index(drop=True) if isinstance(y_train, pd.Series) else y_train
        self.y_val = y_val.reset_index(drop=True) if isinstance(y_val, pd.Series) else y_val
        self.y_test = y_test.reset_index(drop=True) if isinstance(y_test, pd.Series) else y_test
        
        print(f"Разделение данных:")
        print(f"Train: {len(self.X_train)} объектов")
        print(f"Validation: {len(self.X_val)} объектов")
        print(f"Test: {len(self.X_test)} объектов")
        print("=" * 60)

        return self.X_train, self.X_val, self.X_test, self.y_train, self.y_val, self.y_test
    
    def get_fold_distributions(self, cv_splits, X_data, feature_columns):
        distributions = {}

        for fold, (train_idx, test_idx) in enumerate(cv_splits, 1):
            fold_data = X_data.iloc[train_idx]
            
            distributions[fold] = {
                'size': len(train_idx),
                'means': {col: fold_data[col].mean() for col in feature_columns},
                'stds': {col: fold_data[col].std() for col in feature_columns},
                'medians': {col: fold_data[col].median() for col in feature_columns},
                'q25': {col: fold_data[col].quantile(0.25) for col in feature_columns},
                'q75': {col: fold_data[col].quantile(0.75) for col in feature_columns}
            }
        
        return distributions
    
    def _get_dataframes_from_indices(self, cv_splits, X_data, y_data):
        """
        Преобразует индексы в DataFrame'ы для каждого фолда
        """
        dataframes = []
        
        for fold, (train_idx, test_idx) in enumerate(cv_splits, 1):
            max_idx = len(X_data) - 1
            if max(train_idx) > max_idx or max(test_idx) > max_idx:
                print(f"Предупреждение: индексы выходят за пределы данных")
                print(f"Max индекс в данных: {max_idx}")
                print(f"Max train индекс: {max(train_idx)}")
                print(f"Max test индекс: {max(test_idx)}")
                continue
            
            X_train_fold = X_data.iloc[train_idx].copy()
            X_test_fold = X_data.iloc[test_idx].copy()
            y_train_fold = y_data.iloc[train_idx].copy() if isinstance(y_data, pd.Series) else y_data[train_idx]
            y_test_fold = y_data.iloc[test_idx].copy() if isinstance(y_data, pd.Series) else y_data[test_idx]
            
            dataframes.append({
                'fold': fold,
                'X_train': X_train_fold,
                'X_test': X_test_fold,
                'y_train': y_train_fold,
                'y_test': y_test_fold,
                'train_indices': train_idx,
                'test_indices': test_idx
            })
        
        return dataframes
    
    def compare_kfold(self, k=5):
        print("\n" + "=" * 60)
        print("МЕТОД 1: K-Fold кросс-валидация")
        print("=" * 60)
        
        start_time = time.time()
        my_splits = self.cv.kfold_split(
            X=self.X_train, 
            y=self.y_train, 
            k=k, 
            shuffle=True
        )
        my_time = time.time() - start_time
        my_folds = self._get_dataframes_from_indices(my_splits, self.X_train, self.y_train)

        print("\nSKLEARN:")
        start_time = time.time()
        kf = KFold(n_splits=k, shuffle=True, random_state=self.random_state)
        skf_splits = list(kf.split(self.X_train, self.y_train))
        skf_time = time.time() - start_time
        skf_folds = self._get_dataframes_from_indices(skf_splits, self.X_train, self.y_train)
        
        self.timings['kfold'] = {'my': my_time, 'sklearn': skf_time}
        
        print(f"\nВремя выполнения:")
        print(f"Моя реализация: {my_time:.4f} сек")
        print(f"Sklearn:         {skf_time:.4f} сек")
        print(f"Разница:         {abs(my_time - skf_time):.4f} сек")
        
        return my_folds, skf_folds
    
    def compare_group_kfold(self, group_field='bedrooms', k=5):
        print("\n" + "=" * 60)
        print(f"МЕТОД 2: Групповая K-Fold (group_field='{group_field}')")
        print("=" * 60)
        
        start_time = time.time()
        my_splits = self.cv.group_kfold_split(
            X=self.X_train, 
            y=self.y_train, 
            group_field=group_field, 
            k=k
        )
        my_time = time.time() - start_time
        my_folds = self._get_dataframes_from_indices(my_splits, self.X_train, self.y_train)

        print("\nSKLEARN:")
        start_time = time.time()
        gkf = GroupKFold(n_splits=k)
        groups = self.X_train[group_field].values
        skf_splits = list(gkf.split(self.X_train, groups=groups))
        skf_time = time.time() - start_time
        skf_folds = self._get_dataframes_from_indices(skf_splits, self.X_train, self.y_train)
        
        self.timings['group'] = {'my': my_time, 'sklearn': skf_time}
        
        print(f"\nВремя выполнения:")
        print(f"Моя реализация: {my_time:.4f} сек")
        print(f"Sklearn:         {skf_time:.4f} сек")
        print(f"Разница:         {abs(my_time - skf_time):.4f} сек")
        
        return my_folds, skf_folds
    
    def compare_stratified_kfold(self, stratify_field='bedrooms', k=5):
        print("\n" + "=" * 60)
        print(f"МЕТОД 3: Стратифицированная K-Fold (stratify_field='{stratify_field}')")
        print("=" * 60)
        
        start_time = time.time()
        my_splits = self.cv.stratified_kfold_split(
            X=self.X_train,
            y=self.y_train,
            stratify_field=stratify_field,
            k=k,
            shuffle=True
        )
        my_time = time.time() - start_time
        my_folds = self._get_dataframes_from_indices(my_splits, self.X_train, self.y_train)

        print("\nSKLEARN:")
        start_time = time.time()
        skf = StratifiedKFold(n_splits=k, shuffle=True, random_state=self.random_state)
        stratify_values = self.X_train[stratify_field].values
        skf_splits = list(skf.split(self.X_train, y=stratify_values))
        skf_time = time.time() - start_time
        skf_folds = self._get_dataframes_from_indices(skf_splits, self.X_train, self.y_train)
        
        self.timings['stratified'] = {'my': my_time, 'sklearn': skf_time}
        
        print(f"\nВремя выполнения:")
        print(f"Моя реализация: {my_time:.4f} сек")
        print(f"Sklearn:         {skf_time:.4f} сек")
        print(f"Разница:         {abs(my_time - skf_time):.4f} сек")
        
        return my_folds, skf_folds
    
    def compare_time_series_split(self, date_field='created', k=5):
        print("\n" + "=" * 60)
        print(f"МЕТОД 4: Временная K-Fold (date_field='{date_field}')")
        print("=" * 60)
        
        start_time = time.time()
        my_splits = self.cv.time_series_split(
            X=self.X_train, 
            date_field=date_field, 
            k=k
        )
        my_time = time.time() - start_time
        my_folds = self._get_dataframes_from_indices(my_splits, self.X_train, self.y_train)

        print("\nSKLEARN:")
        start_time = time.time()
        tscv = TimeSeriesSplit(n_splits=k)
        skf_splits = list(tscv.split(self.X_train))
        skf_time = time.time() - start_time
        skf_folds = self._get_dataframes_from_indices(skf_splits, self.X_train, self.y_train)
        
        self.timings['time'] = {'my': my_time, 'sklearn': skf_time}
        
        print(f"\nВремя выполнения:")
        print(f"Моя реализация: {my_time:.4f} сек")
        print(f"Sklearn:         {skf_time:.4f} сек")
        print(f"Разница:         {abs(my_time - skf_time):.4f} сек")
        
        return my_folds, skf_folds
    
    def compare_distributions(self, my_folds, skf_folds, feature_columns=None, method_name="Метод"):
        if feature_columns is None:
            feature_columns = self.feature_columns
        
        print(f"\n{'='*60}")
        print(f"СРАВНЕНИЕ РАСПРЕДЕЛЕНИЙ: {method_name}")
        print("=" * 60)
        
        if len(my_folds) == 0 or len(skf_folds) == 0:
            print("Нет данных для сравнения (пустые фолды)")
            return None, None
        
        my_splits = [(fold['train_indices'], fold['test_indices']) for fold in my_folds]
        skf_splits = [(fold['train_indices'], fold['test_indices']) for fold in skf_folds]
        
        my_dist = self.get_fold_distributions(my_splits, self.X_train, feature_columns)
        skf_dist = self.get_fold_distributions(skf_splits, self.X_train, feature_columns)
        
        for feature in feature_columns:
            self._compare_single_feature(my_dist, skf_dist, feature)
        
        return my_dist, skf_dist
    
    def _compare_single_feature(self, my_dist, skf_dist, feature):
        my_means = [my_dist[f]['means'][feature] for f in my_dist]
        skf_means = [skf_dist[f]['means'][feature] for f in skf_dist]
        
        my_variation = np.std(my_means)
        skf_variation = np.std(skf_means)
        
        print(f"\nПризнак: {feature}")
        print(f"Средние (моя реализация): {[round(m, 2) for m in my_means]}")
        print(f"Средние (sklearn): {[round(m, 2) for m in skf_means]}")
        print(f"Разница средних: {round(np.mean(my_means) - np.mean(skf_means), 4)}")
        print(f"Вариация (моя реализация): {round(my_variation, 4)}")
        print(f"Вариация (sklearn): {round(skf_variation, 4)}")
        
        if abs(my_variation - skf_variation) < 0.01:
            print("Распределения согласованы")
        else:
            print("Распределения отличаются")

    def run_all_comparisons(self, k=5):
        self.split_data(val_size=0.2, test_size=0.2)
        
        comparisons = {}
        
        # K-Fold
        my_folds, skf_folds = self.compare_kfold(k=k)
        if len(my_folds) > 0 and len(skf_folds) > 0:
            comparisons['kfold'] = self.compare_distributions(
                my_folds, skf_folds, 
                method_name="K-Fold"
            )
        else:
            print("K-Fold: недостаточно данных для сравнения")
        
        # Group K-Fold
        my_folds, skf_folds = self.compare_group_kfold(k=k)
        if len(my_folds) > 0 and len(skf_folds) > 0:
            comparisons['group'] = self.compare_distributions(
                my_folds, skf_folds, 
                method_name="Group K-Fold"
            )
        else:
            print("Group K-Fold: недостаточно данных для сравнения")
        
        # Stratified K-Fold
        my_folds, skf_folds = self.compare_stratified_kfold(k=k)
        if len(my_folds) > 0 and len(skf_folds) > 0:
            comparisons['stratified'] = self.compare_distributions(
                my_folds, skf_folds, 
                method_name="Stratified K-Fold"
            )
        else:
            print("Stratified K-Fold: недостаточно данных для сравнения")
        
        # Time Series Split
        if 'created' in self.X_train.columns:
            my_folds, skf_folds = self.compare_time_series_split(k=k)
            if len(my_folds) > 0 and len(skf_folds) > 0:
                comparisons['time'] = self.compare_distributions(
                    my_folds, skf_folds, 
                    method_name="Time Series Split"
                )
            else:
                print("Time Series Split: недостаточно данных для сравнения")
        
        return comparisons, self.timings

In [23]:
comparator = CrossValidatorComparison(X, y, random_state=42)
results, timings = comparator.run_all_comparisons(k=5)

Разделение данных:
Train: 29027 объектов
Validation: 9676 объектов
Test: 9676 объектов
============================================================

============================================================
МЕТОД 1: K-Fold кросс-валидация
============================================================
Fold 1: Train 23221 объектов Test 5806 объектов
Fold 2: Train 23221 объектов Test 5806 объектов
Fold 3: Train 23222 объектов Test 5805 объектов
Fold 4: Train 23222 объектов Test 5805 объектов
Fold 5: Train 23222 объектов Test 5805 объектов

SKLEARN:

Время выполнения:
Моя реализация: 0.0005 сек
Sklearn:         0.0012 сек
Разница:         0.0007 сек

============================================================
СРАВНЕНИЕ РАСПРЕДЕЛЕНИЙ: K-Fold
============================================================

Признак: bathrooms
Средние (моя реализация): [np.float64(1.2), np.float64(1.2), np.float64(1.19), np.float64(1.2), np.float64(1.2)]
Средние (sklearn): [np.float64(1.2), np.float64(1.2), np.float64(1.19), np.float64(1.2), np.float64(1.2)]
Разница средних: 0.0
Вариация (моя реализация): 0.0011
Вариация (sklearn): 0.0011
Распределения согласованы

Признак: bedrooms
Средние (моя реализация): [np.float64(1.53), np.float64(1.54), np.float64(1.54), np.float64(1.54), np.float64(1.54)]
Средние (sklearn): [np.float64(1.53), np.float64(1.54), np.float64(1.54), np.float64(1.54), np.float64(1.54)]
Разница средних: 0.0
Вариация (моя реализация): 0.0028
Вариация (sklearn): 0.0028
Распределения согласованы

Признак: latitude
Средние (моя реализация): [np.float64(40.74), np.float64(40.74), np.float64(40.74), np.float64(40.73), np.float64(40.74)]
Средние (sklearn): [np.float64(40.74), np.float64(40.74), np.float64(40.74), np.float64(40.73), np.float64(40.74)]
Разница средних: 0.0
Вариация (моя реализация): 0.0008
Вариация (sklearn): 0.0008
Распределения согласованы

============================================================
МЕТОД 2: Групповая K-Fold (group_field='bedrooms')
============================================================
Группировка по полю: 'bedrooms'
Fold 1: Train 19735 объектов (7 групп) Test 9292 объектов (2 групп)
Fold 2: Train 23424 объектов (7 групп) Test 5603 объектов (2 групп)
Fold 3: Train 20213 объектов (7 групп) Test 8814 объектов (2 групп)
Fold 4: Train 23732 объектов (7 групп) Test 5295 объектов (2 групп)
Fold 5: Train 29004 объектов (8 групп) Test 23 объектов (1 групп)

SKLEARN:

Время выполнения:
Моя реализация: 0.0040 сек
Sklearn:         0.0015 сек
Разница:         0.0025 сек

============================================================
СРАВНЕНИЕ РАСПРЕДЕЛЕНИЙ: Group K-Fold
============================================================

Признак: bathrooms
Средние (моя реализация): [np.float64(1.28), np.float64(1.24), np.float64(1.17), np.float64(1.1), np.float64(1.19)]
Средние (sklearn): [np.float64(1.28), np.float64(1.17), np.float64(1.24), np.float64(1.14), np.float64(1.16)]
Разница средних: -0.0016
Вариация (моя реализация): 0.0595
Вариация (sklearn): 0.0535
Распределения согласованы

Признак: bedrooms
Средние (моя реализация): [np.float64(1.79), np.float64(1.88), np.float64(1.34), np.float64(1.17), np.float64(1.54)]
Средние (sklearn): [np.float64(1.79), np.float64(1.34), np.float64(1.9), np.float64(1.29), np.float64(1.42)]
Разница средних: -0.0057
Вариация (моя реализация): 0.2678
Вариация (sklearn): 0.2479
Распределения отличаются

Признак: latitude
Средние (моя реализация): [np.float64(40.74), np.float64(40.73), np.float64(40.74), np.float64(40.73), np.float64(40.74)]
Средние (sklearn): [np.float64(40.74), np.float64(40.74), np.float64(40.73), np.float64(40.73), np.float64(40.74)]
Разница средних: -0.0001
Вариация (моя реализация): 0.0024
Вариация (sklearn): 0.0021
Распределения согласованы

============================================================
МЕТОД 3: Стратифицированная K-Fold (stratify_field='bedrooms')
============================================================
Стратификация по полю: 'bedrooms'
Fold 1: Train 23224 объектов Test 5803 объектов
Распределение bedrooms:
0 bedrooms: Все данные=18.9%, Train=18.9%, Test=18.9%
1 bedrooms: Все данные=32.0%, Train=32.0%, Test=32.0%
2 bedrooms: Все данные=30.4%, Train=30.4%, Test=30.4%
3 bedrooms: Все данные=14.5%, Train=14.5%, Test=14.5%
4 bedrooms: Все данные=3.7%, Train=3.7%, Test=3.7%
5 bedrooms: Все данные=0.4%, Train=0.4%, Test=0.4%
6 bedrooms: Все данные=0.1%, Train=0.1%, Test=0.1%
7 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%
8 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%
Fold 2: Train 23217 объектов Test 5810 объектов
Распределение bedrooms:
0 bedrooms: Все данные=18.9%, Train=18.9%, Test=18.8%
1 bedrooms: Все данные=32.0%, Train=32.0%, Test=32.0%
2 bedrooms: Все данные=30.4%, Train=30.4%, Test=30.3%
3 bedrooms: Все данные=14.5%, Train=14.5%, Test=14.5%
4 bedrooms: Все данные=3.7%, Train=3.7%, Test=3.7%
5 bedrooms: Все данные=0.4%, Train=0.4%, Test=0.4%
6 bedrooms: Все данные=0.1%, Train=0.1%, Test=0.1%
7 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%
8 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%
Fold 3: Train 23221 объектов Test 5806 объектов
Распределение bedrooms:
0 bedrooms: Все данные=18.9%, Train=18.9%, Test=18.9%
1 bedrooms: Все данные=32.0%, Train=32.0%, Test=32.0%
2 bedrooms: Все данные=30.4%, Train=30.4%, Test=30.4%
3 bedrooms: Все данные=14.5%, Train=14.5%, Test=14.5%
4 bedrooms: Все данные=3.7%, Train=3.7%, Test=3.7%
5 bedrooms: Все данные=0.4%, Train=0.4%, Test=0.4%
6 bedrooms: Все данные=0.1%, Train=0.1%, Test=0.1%
7 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%
8 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%
Fold 4: Train 23225 объектов Test 5802 объектов
Распределение bedrooms:
0 bedrooms: Все данные=18.9%, Train=18.9%, Test=18.9%
1 bedrooms: Все данные=32.0%, Train=32.0%, Test=32.0%
2 bedrooms: Все данные=30.4%, Train=30.4%, Test=30.4%
3 bedrooms: Все данные=14.5%, Train=14.5%, Test=14.5%
4 bedrooms: Все данные=3.7%, Train=3.7%, Test=3.7%
5 bedrooms: Все данные=0.4%, Train=0.4%, Test=0.4%
6 bedrooms: Все данные=0.1%, Train=0.1%, Test=0.1%
7 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%
8 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%
Fold 5: Train 23221 объектов Test 5806 объектов
Распределение bedrooms:
0 bedrooms: Все данные=18.9%, Train=18.9%, Test=18.9%
1 bedrooms: Все данные=32.0%, Train=32.0%, Test=32.0%
2 bedrooms: Все данные=30.4%, Train=30.4%, Test=30.4%
3 bedrooms: Все данные=14.5%, Train=14.5%, Test=14.5%
4 bedrooms: Все данные=3.7%, Train=3.7%, Test=3.7%
5 bedrooms: Все данные=0.4%, Train=0.4%, Test=0.4%
6 bedrooms: Все данные=0.1%, Train=0.1%, Test=0.1%
7 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%
8 bedrooms: Все данные=0.0%, Train=0.0%, Test=0.0%

SKLEARN:

Время выполнения:
Моя реализация: 0.0235 сек
Sklearn:         0.0028 сек
Разница:         0.0207 сек

============================================================
СРАВНЕНИЕ РАСПРЕДЕЛЕНИЙ: Stratified K-Fold
============================================================

Признак: bathrooms
Средние (моя реализация): [np.float64(1.2), np.float64(1.2), np.float64(1.2), np.float64(1.2), np.float64(1.19)]
Средние (sklearn): [np.float64(1.2), np.float64(1.2), np.float64(1.2), np.float64(1.2), np.float64(1.2)]
Разница средних: -0.0
Вариация (моя реализация): 0.0006
Вариация (sklearn): 0.0008
Распределения согласованы

Признак: bedrooms
Средние (моя реализация): [np.float64(1.54), np.float64(1.54), np.float64(1.54), np.float64(1.54), np.float64(1.54)]
Средние (sklearn): [np.float64(1.54), np.float64(1.54), np.float64(1.54), np.float64(1.54), np.float64(1.54)]
Разница средних: -0.0
Вариация (моя реализация): 0.0003
Вариация (sklearn): 0.0001
Распределения согласованы

Признак: latitude
Средние (моя реализация): [np.float64(40.74), np.float64(40.73), np.float64(40.74), np.float64(40.74), np.float64(40.74)]
Средние (sklearn): [np.float64(40.73), np.float64(40.74), np.float64(40.74), np.float64(40.73), np.float64(40.74)]
Разница средних: -0.0
Вариация (моя реализация): 0.0015
Вариация (sklearn): 0.0026
Распределения согласованы

============================================================
МЕТОД 4: Временная K-Fold (date_field='created')
============================================================
Fold 2: Train 4837 объектов Test 4837 объектов
Fold 3: Train 9674 объектов Test 4837 объектов
Fold 4: Train 14511 объектов Test 4837 объектов
Fold 5: Train 19348 объектов Test 4837 объектов
Fold 6: Train 24185 объектов Test 4837 объектов

SKLEARN:

Время выполнения:
Моя реализация: 0.0051 сек
Sklearn:         0.0000 сек
Разница:         0.0051 сек

============================================================
СРАВНЕНИЕ РАСПРЕДЕЛЕНИЙ: Time Series Split
============================================================

Признак: bathrooms
Средние (моя реализация): [np.float64(1.2), np.float64(1.2), np.float64(1.2), np.float64(1.2), np.float64(1.2)]
Средние (sklearn): [np.float64(1.2), np.float64(1.2), np.float64(1.2), np.float64(1.2), np.float64(1.2)]
Разница средних: 0.0001
Вариация (моя реализация): 0.0009
Вариация (sklearn): 0.0009
Распределения согласованы

Признак: bedrooms
Средние (моя реализация): [np.float64(1.56), np.float64(1.54), np.float64(1.54), np.float64(1.54), np.float64(1.55)]
Средние (sklearn): [np.float64(1.56), np.float64(1.54), np.float64(1.54), np.float64(1.54), np.float64(1.55)]
Разница средних: 0.0
Вариация (моя реализация): 0.0068
Вариация (sklearn): 0.0069
Распределения согласованы

Признак: latitude
Средние (моя реализация): [np.float64(40.75), np.float64(40.74), np.float64(40.73), np.float64(40.73), np.float64(40.74)]
Средние (sklearn): [np.float64(40.75), np.float64(40.74), np.float64(40.73), np.float64(40.73), np.float64(40.74)]
Разница средних: -0.0
Вариация (моя реализация): 0.007
Вариация (sklearn): 0.007
Распределения согласованы

**Вывод:** Все реализации совпали, кроме группового разбиения, это не критично. Связано с тем, что в первую очередь многие классы включают в себя 1 объект. Также алгоритмические различия в реализациях: Sklearn использует оптимизированный алгоритм. Моя реализация использует более простой циклический алгоритм.

Тк у нас подразумевается решение задачи регрессии, то будет **лучшим K-Fold метод**. Также подошел бы стратифицированный метод, тк он хорошо себя показывает с нашими несбалансированными данными. Групповой и временной методы нам не актуальны, тк в данных отстувуют специальное разделение по группам или дата/время.

## 6. Feature Selection

Нормализуем признаки и делим данные на 3 части в соотношении 60/20/20

In [24]:
X_numeric = X.select_dtypes(include=['float64', 'int64'])

In [25]:
def measure_stability(model, X, y, n_splits=5):
    kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)

    rmse_scores = -cross_val_score(model, X, y, cv=kf, scoring='neg_root_mean_squared_error', n_jobs=-1)

    r2_scores = cross_val_score(model, X, y, cv=kf, scoring='r2',n_jobs=-1)
    
    return {
        'rmse_mean': np.mean(rmse_scores),
        'rmse_std': np.std(rmse_scores),
        'r2_mean': np.mean(r2_scores),
        'r2_std': np.std(r2_scores)
    }

In [26]:
splitter = DataSplitter()
X_train, X_valid, X_test, y_train, y_valid, y_test = splitter.train_valid_test_random_split(X_numeric, y, validation_size=0.2, test_size=0.2)

Обучающая выборка: 29027 объектов
Валидационная выборка: 9676 объектов
Тестовая выборка: 9676 объектов

In [27]:
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)
X_test_scaled = scaler.transform(X_test)

Обучаем модель Lasso:

In [28]:
def train_lasso_model(X_train_scaled, y_train, X_valid_scaled, y_valid, alpha=0.0001):
    start_time_lasso = time.time()
    lasso = Lasso(alpha=alpha, random_state=42, max_iter=10000)
    lasso.fit(X_train_scaled, y_train)
    
    y_train_pred = lasso.predict(X_train_scaled)
    y_valid_pred = lasso.predict(X_valid_scaled)
    time_total_lasso = time.time() - start_time_lasso
    
    train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
    val_rmse = np.sqrt(mean_squared_error(y_valid, y_valid_pred))
    train_r2 = r2_score(y_train, y_train_pred)
    val_r2 = r2_score(y_valid, y_valid_pred)
    
    return {
        'model': lasso,
        'coefficients': lasso.coef_,
        'intercept': lasso.intercept_,
        'train_rmse': train_rmse,
        'val_rmse': val_rmse,
        'train_r2': train_r2,
        'val_r2': val_r2,
        'time_training': time_total_lasso,
        'n_features_used': np.sum(lasso.coef_ != 0)
    }

In [29]:
lasso_results = train_lasso_model(X_train_scaled, y_train, X_valid_scaled, y_valid, alpha=0.0001)
print(f"Train RMSE: {lasso_results['train_rmse']:.2f}")
print(f"Validation RMSE: {lasso_results['val_rmse']:.2f}")
print(f"Train R²: {lasso_results['train_r2']:.4f}")
print(f"Validation R²: {lasso_results['val_r2']:.4f}")
print(f"Использовано признаков: {lasso_results['n_features_used']} из {X_train.shape[1]}")
print(f"Время обучения: {lasso_results['time_training']:.4f} сек")
print("Измерение стабильности (5-fold CV) для всех признаков")
stability_all = measure_stability(Lasso(alpha=0.0001, random_state=42, max_iter=10000), X_train_scaled, y_train)
print(f"RMSE: {stability_all['rmse_mean']:.4f} ± {stability_all['rmse_std']:.4f}")
print(f"R²:   {stability_all['r2_mean']:.4f} ± {stability_all['r2_std']:.4f}")

Train RMSE: 1030.20
Validation RMSE: 1034.07
Train R²: 0.5860
Validation R²: 0.5788
Использовано признаков: 26 из 26
Время обучения: 0.0089 сек
Измерение стабильности (5-fold CV) для всех признаков
RMSE: 1048.7114 ± 40.6445
R²:   0.5701 ± 0.0326

Выбираем топ-10 важных признаков и обучаем модель Lasso:

In [30]:
feature_importance = pd.DataFrame({
    'feature': X_train.columns,
    'coefficient': lasso_results['coefficients'],
    'abs_coefficient': np.abs(lasso_results['coefficients'])
}).sort_values('abs_coefficient', ascending=False)

print("\nТОП-10 ПРИЗНАКОВ:")
print(feature_importance.head(10).to_string(index=False))

top_10_features = feature_importance.head(10)['feature'].tolist()

ТОП-10 ПРИЗНАКОВ:
          feature   coefficient  abs_coefficient
        bathrooms  15702.414013     15702.414013
        longitude -11841.881754     11841.881754
         latitude  -7461.511439      7461.511439
         bedrooms   3709.350423      3709.350423
          Doorman    627.660197       627.660197
    LaundryinUnit    451.167123       451.167123
LaundryInBuilding   -330.286976       330.286976
HighSpeedInternet   -251.470127       251.470127
   interest_level   -235.500831       235.500831
    FitnessCenter    226.700443       226.700443

In [31]:
X_train_top10 = X_train[top_10_features]
X_valid_top10 = X_valid[top_10_features]
X_test_top10 = X_test[top_10_features]

In [32]:
scaler_top10 = MinMaxScaler()
X_train_top10_scaled = scaler_top10.fit_transform(X_train_top10)
X_valid_top10_scaled = scaler_top10.transform(X_valid_top10)
X_test_top10_scaled = scaler_top10.transform(X_test_top10)

In [33]:
lasso_top10_results = train_lasso_model(X_train_top10_scaled, y_train, X_valid_top10_scaled, y_valid, alpha=0.0001)

In [34]:
y_train_pred_all = lasso_results['model'].predict(X_train_scaled)
y_val_pred_all = lasso_results['model'].predict(X_valid_scaled)
y_test_pred_all = lasso_results['model'].predict(X_test_scaled)

train_rmse_all = np.sqrt(mean_squared_error(y_train, y_train_pred_all))
val_rmse_all = np.sqrt(mean_squared_error(y_valid, y_val_pred_all))
test_rmse_all = np.sqrt(mean_squared_error(y_test, y_test_pred_all))

train_r2_all = r2_score(y_train, y_train_pred_all)
val_r2_all = r2_score(y_valid, y_val_pred_all)
test_r2_all = r2_score(y_test, y_test_pred_all)

train_mae_all = mean_absolute_error(y_train, y_train_pred_all)
val_mae_all = mean_absolute_error(y_valid, y_val_pred_all)
test_mae_all = mean_absolute_error(y_test, y_test_pred_all)

y_train_pred_top10 = lasso_top10_results['model'].predict(X_train_top10_scaled)
y_val_pred_top10 = lasso_top10_results['model'].predict(X_valid_top10_scaled)
y_test_pred_top10 = lasso_top10_results['model'].predict(X_test_top10_scaled)

train_rmse_top10 = np.sqrt(mean_squared_error(y_train, y_train_pred_top10))
val_rmse_top10 = np.sqrt(mean_squared_error(y_valid, y_val_pred_top10))
test_rmse_top10 = np.sqrt(mean_squared_error(y_test, y_test_pred_top10))

train_r2_top10 = r2_score(y_train, y_train_pred_top10)
val_r2_top10 = r2_score(y_valid, y_val_pred_top10)
test_r2_top10 = r2_score(y_test, y_test_pred_top10)

train_mae_top10 = mean_absolute_error(y_train, y_train_pred_top10)
val_mae_top10 = mean_absolute_error(y_valid, y_val_pred_top10)
test_mae_top10 = mean_absolute_error(y_test, y_test_pred_top10)

stability_top10 = measure_stability(Lasso(alpha=0.0001, random_state=42, max_iter=10000), X_train_top10_scaled, y_train)

comparison_df = pd.DataFrame({
    'Метрика': [
        'RMSE (Train)',
        'RMSE (Validation)', 
        'RMSE (Test)',
        'R² (Train)',
        'R² (Validation)',
        'R² (Test)',
        'MAE (Train)',
        'MAE (Validation)',
        'MAE (Test)',
        'Время обучения (сек)',
        'Стабильность RMSE (std)',
        'Стабильность R² (std)'
    ],
    'Все признаки': [
        f"{train_rmse_all:.2f}",
        f"{val_rmse_all:.2f}",
        f"{test_rmse_all:.2f}",
        f"{train_r2_all:.4f}",
        f"{val_r2_all:.4f}",
        f"{test_r2_all:.4f}",
        f"{train_mae_all:.2f}",
        f"{val_mae_all:.2f}",
        f"{test_mae_all:.2f}",
        f"{lasso_results['time_training']:.4f}",
        f"{stability_all['rmse_std']:.4f}",
        f"{stability_all['r2_std']:.4f}"
    ],
    'Топ-10 признаков': [
        f"{train_rmse_top10:.2f}",
        f"{val_rmse_top10:.2f}",
        f"{test_rmse_top10:.2f}",
        f"{train_r2_top10:.4f}",
        f"{val_r2_top10:.4f}",
        f"{test_r2_top10:.4f}",
        f"{train_mae_top10:.2f}",
        f"{val_mae_top10:.2f}",
        f"{test_mae_top10:.2f}",
        f"{lasso_top10_results['time_training']:.4f}",
        f"{stability_top10['rmse_std']:.4f}",
        f"{stability_top10['r2_std']:.4f}"
    ]
})

print(comparison_df.to_string(index=False))

                Метрика Все признаки Топ-10 признаков
           RMSE (Train)      1030.20          1044.19
      RMSE (Validation)      1034.07          1047.25
            RMSE (Test)      1039.50          1055.87
             R² (Train)       0.5860           0.5747
        R² (Validation)       0.5788           0.5680
              R² (Test)       0.5733           0.5597
            MAE (Train)       707.39           717.53
       MAE (Validation)       709.62           718.04
             MAE (Test)       710.36           723.44
   Время обучения (сек)       0.0089           0.0046
Стабильность RMSE (std)      40.6445          41.5275
  Стабильность R² (std)       0.0326           0.0340

Реализуем метод простого отбора признаков по соотношению NaN в признаках и корреляции и снова обучаем Lasso:

In [35]:
def select_features_corr(X, y, nan_threshold=0.5, top_k=10):
    X_selected_corr = X_numeric.copy()
    nan_ratio = X_selected_corr.isnull().mean()
    cols_to_keep = nan_ratio[nan_ratio <= nan_threshold].index.tolist()
    X_selected_corr = X_selected_corr[cols_to_keep]
    print(f"Удалено признаков с > {nan_threshold*100}% NaN: {len(X.columns) - len(cols_to_keep)}")

    correlations = X_selected_corr.corrwith(y).abs().sort_values(ascending=False)

    top_features = correlations.head(top_k).index.tolist()
    X_selected_corr = X_selected_corr[top_features]
    
    top_correlations = correlations.head(top_k).reset_index()
    top_correlations.columns = ['Признак', 'Корреляция']
    
    print(f"\nТОП-{top_k} ПРИЗНАКОВ ПО КОРРЕЛЯЦИИ:")
    print(top_correlations.to_string(index=False))
    print(f"\nИтоговое количество признаков: {X_selected_corr.shape[1]}")
    return X_selected_corr, top_features, correlations

In [36]:
X_selected_corr, selected_features, correlations = select_features_corr(X_numeric, y, nan_threshold=0.5, top_k=10)

Удалено признаков с > 50.0% NaN: 0

ТОП-10 ПРИЗНАКОВ ПО КОРРЕЛЯЦИИ:
          Признак  Корреляция
        bathrooms    0.671943
         bedrooms    0.545948
          Doorman    0.281918
    LaundryinUnit    0.260340
    FitnessCenter    0.233469
       Dishwasher    0.225491
       DiningRoom    0.224907
         Elevator    0.215688
     OutdoorSpace    0.152963
LaundryinBuilding    0.140723

Итоговое количество признаков: 10

In [37]:
X_train_corr, X_valid_corr, X_test_corr, y_train, y_valid, y_test = splitter.train_valid_test_random_split(X_selected_corr, y, validation_size=0.2, test_size=0.2)

Обучающая выборка: 29027 объектов
Валидационная выборка: 9676 объектов
Тестовая выборка: 9676 объектов

In [38]:
scaler_corr = MinMaxScaler()
X_train_corr_scaled = scaler_corr.fit_transform(X_train_corr)
X_valid_corr_scaled = scaler_corr.transform(X_valid_corr)
X_test_corr_scaled = scaler_corr.transform(X_test_corr)

X_train_corr_scaled = pd.DataFrame(X_train_corr_scaled, columns=X_train_corr.columns, index=X_train_corr.index)
X_valid_corr_scaled = pd.DataFrame(X_valid_corr_scaled, columns=X_valid_corr.columns, index=X_valid_corr.index)
X_test_corr_scaled = pd.DataFrame(X_test_corr_scaled, columns=X_test_corr.columns, index=X_test_corr.index)

In [39]:
lasso_corr_results = train_lasso_model(X_train_corr_scaled, y_train, X_valid_corr_scaled, y_valid, alpha=0.0001)

In [40]:
y_train_pred_all = lasso_results['model'].predict(X_train_scaled)
y_val_pred_all = lasso_results['model'].predict(X_valid_scaled)
y_test_pred_all = lasso_results['model'].predict(X_test_scaled)

train_rmse_all = np.sqrt(mean_squared_error(y_train, y_train_pred_all))
val_rmse_all = np.sqrt(mean_squared_error(y_valid, y_val_pred_all))
test_rmse_all = np.sqrt(mean_squared_error(y_test, y_test_pred_all))

train_r2_all = r2_score(y_train, y_train_pred_all)
val_r2_all = r2_score(y_valid, y_val_pred_all)
test_r2_all = r2_score(y_test, y_test_pred_all)

train_mae_all = mean_absolute_error(y_train, y_train_pred_all)
val_mae_all = mean_absolute_error(y_valid, y_val_pred_all)
test_mae_all = mean_absolute_error(y_test, y_test_pred_all)

y_train_pred_top10 = lasso_top10_results['model'].predict(X_train_top10_scaled)
y_val_pred_top10 = lasso_top10_results['model'].predict(X_valid_top10_scaled)
y_test_pred_top10 = lasso_top10_results['model'].predict(X_test_top10_scaled)

train_rmse_top10 = np.sqrt(mean_squared_error(y_train, y_train_pred_top10))
val_rmse_top10 = np.sqrt(mean_squared_error(y_valid, y_val_pred_top10))
test_rmse_top10 = np.sqrt(mean_squared_error(y_test, y_test_pred_top10))

train_r2_top10 = r2_score(y_train, y_train_pred_top10)
val_r2_top10 = r2_score(y_valid, y_val_pred_top10)
test_r2_top10 = r2_score(y_test, y_test_pred_top10)

train_mae_top10 = mean_absolute_error(y_train, y_train_pred_top10)
val_mae_top10 = mean_absolute_error(y_valid, y_val_pred_top10)
test_mae_top10 = mean_absolute_error(y_test, y_test_pred_top10)

y_train_pred_corr = lasso_corr_results['model'].predict(X_train_corr_scaled)
y_val_pred_corr = lasso_corr_results['model'].predict(X_valid_corr_scaled)
y_test_pred_corr = lasso_corr_results['model'].predict(X_test_corr_scaled)

train_rmse_corr = np.sqrt(mean_squared_error(y_train, y_train_pred_corr))
val_rmse_corr = np.sqrt(mean_squared_error(y_valid, y_val_pred_corr))
test_rmse_corr = np.sqrt(mean_squared_error(y_test, y_test_pred_corr))

train_r2_corr = r2_score(y_train, y_train_pred_corr)
val_r2_corr = r2_score(y_valid, y_val_pred_corr)
test_r2_corr = r2_score(y_test, y_test_pred_corr)

train_mae_corr = mean_absolute_error(y_train, y_train_pred_corr)
val_mae_corr = mean_absolute_error(y_valid, y_val_pred_corr)
test_mae_corr = mean_absolute_error(y_test, y_test_pred_corr)

stability_corr = measure_stability(Lasso(alpha=0.0001, random_state=42, max_iter=10000), X_train_corr_scaled, y_train)

comparison_df = pd.DataFrame({
    'Метрика': [
        'RMSE (Train)',
        'RMSE (Validation)',
        'RMSE (Test)',
        'R² (Train)',
        'R² (Validation)',
        'R² (Test)',
        'MAE (Train)',
        'MAE (Validation)',
        'MAE (Test)',
        'Время обучения (сек)',
        'Стабильность RMSE (std)',
        'Стабильность R² (std)'
    ],
    'Все признаки': [
        f"{train_rmse_all:.2f}",
        f"{val_rmse_all:.2f}",
        f"{test_rmse_all:.2f}",
        f"{train_r2_all:.4f}",
        f"{val_r2_all:.4f}",
        f"{test_r2_all:.4f}",
        f"{train_mae_all:.2f}",
        f"{val_mae_all:.2f}",
        f"{test_mae_all:.2f}",
        f"{lasso_results['time_training']:.4f}",
        f"{stability_all['rmse_std']:.4f}",
        f"{stability_all['r2_std']:.4f}"
    ],
    'Топ-10 признаков': [
        f"{train_rmse_top10:.2f}",
        f"{val_rmse_top10:.2f}",
        f"{test_rmse_top10:.2f}",
        f"{train_r2_top10:.4f}",
        f"{val_r2_top10:.4f}",
        f"{test_r2_top10:.4f}",
        f"{train_mae_top10:.2f}",
        f"{val_mae_top10:.2f}",
        f"{test_mae_top10:.2f}",
        f"{lasso_top10_results['time_training']:.4f}",
        f"{stability_top10['rmse_std']:.4f}",
        f"{stability_top10['r2_std']:.4f}"
    ],
    'Топ-10 corr признаков': [
        f"{train_rmse_corr:.2f}",
        f"{val_rmse_corr:.2f}",
        f"{test_rmse_corr:.2f}",
        f"{train_r2_corr:.4f}",
        f"{val_r2_corr:.4f}",
        f"{test_r2_corr:.4f}",
        f"{train_mae_corr:.2f}",
        f"{val_mae_corr:.2f}",
        f"{test_mae_corr:.2f}",
        f"{lasso_corr_results['time_training']:.4f}",
        f"{stability_corr['rmse_std']:.4f}",
        f"{stability_corr['r2_std']:.4f}"
    ]
})

print(comparison_df.to_string(index=False))

                Метрика Все признаки Топ-10 признаков Топ-10 corr признаков
           RMSE (Train)      1030.20          1044.19               1044.68
      RMSE (Validation)      1034.07          1047.25               1049.83
            RMSE (Test)      1039.50          1055.87               1056.88
             R² (Train)       0.5860           0.5747                0.5743
        R² (Validation)       0.5788           0.5680                0.5659
              R² (Test)       0.5733           0.5597                0.5589
            MAE (Train)       707.39           717.53                720.16
       MAE (Validation)       709.62           718.04                722.45
             MAE (Test)       710.36           723.44                726.59
   Время обучения (сек)       0.0089           0.0046                0.0026
Стабильность RMSE (std)      40.6445          41.5275               25.4389
  Стабильность R² (std)       0.0326           0.0340                0.0166

Реализуем permutation importance метод и снова обучим модель Lasso:

In [41]:
def select_features_permutation(X, y, top_k=10, random_state=42):
    X_selected_pi = X.copy()
    X_train_pi, X_temp_pi, y_train_pi, y_temp_pi = train_test_split(X_selected_pi, y, test_size=0.3, random_state=random_state)
    X_val_pi, X_test_pi, y_val_pi, y_test_pi = train_test_split(X_temp_pi, y_temp_pi, test_size=0.5, random_state=random_state)

    scaler_pi = MinMaxScaler()
    X_train_pi_scaled = scaler_pi.fit_transform(X_train_pi)
    X_val_pi_scaled = scaler_pi.transform(X_val_pi)

    lasso_for_importance = Lasso(alpha=0.001, random_state=random_state, max_iter=10000)
    lasso_for_importance.fit(X_train_pi_scaled, y_train_pi)
    
    perm_importance = permutation_importance(
        lasso_for_importance, 
        X_val_pi_scaled, 
        y_val_pi,
        n_repeats=10,
        random_state=random_state,
        n_jobs=-1
    )
    
    importance_df = pd.DataFrame({
        'Признак': X_selected_pi.columns,
        'Среднее': perm_importance.importances_mean,
        'Стандартное_отклонение': perm_importance.importances_std
    }).sort_values('Среднее', ascending=False)
    
    top_features_pi = importance_df.head(top_k)['Признак'].tolist()
    X_selected_pi = X_selected_pi[top_features_pi]
    
    print(f"\nТОП-{top_k} ПРИЗНАКОВ ПО PERMUTATION IMPORTANCE (Lasso):")
    display_df = importance_df.head(top_k).copy()
    display_df['Среднее'] = display_df['Среднее'].round(4)
    display_df['Стандартное_отклонение'] = display_df['Стандартное_отклонение'].round(4)
    print(display_df[['Признак', 'Среднее', 'Стандартное_отклонение']].to_string(index=False))
    
    print(f"\nИтоговое количество признаков: {X_selected_pi.shape[1]}")
    
    return X_selected_pi, top_features_pi, importance_df

In [42]:
X_selected_pi, top_features_pi, importance_df = select_features_permutation(X_numeric, y, top_k=10,random_state=42)

ТОП-10 ПРИЗНАКОВ ПО PERMUTATION IMPORTANCE (Lasso):
          Признак  Среднее  Стандартное_отклонение
        bathrooms   0.3902                  0.0094
         bedrooms   0.2000                  0.0060
          Doorman   0.0693                  0.0014
    LaundryinUnit   0.0199                  0.0017
         Elevator   0.0096                  0.0010
LaundryinBuilding   0.0093                  0.0007
    FitnessCenter   0.0091                  0.0013
            NoFee   0.0062                  0.0008
   HardwoodFloors   0.0059                  0.0006
      DogsAllowed   0.0057                  0.0007

Итоговое количество признаков: 10

In [43]:
X_train_pi, X_valid_pi, X_test_pi, y_train, y_valid, y_test = splitter.train_valid_test_random_split(X_selected_pi, y, validation_size=0.2, test_size=0.2)

Обучающая выборка: 29027 объектов
Валидационная выборка: 9676 объектов
Тестовая выборка: 9676 объектов

In [44]:
scaler_pi = MinMaxScaler()
X_train_pi_scaled = scaler_pi.fit_transform(X_train_pi)
X_valid_pi_scaled = scaler_pi.transform(X_valid_pi)
X_test_pi_scaled = scaler_pi.transform(X_test_pi)

X_train_pi_scaled = pd.DataFrame(X_train_pi_scaled, columns=X_train_pi.columns, index=X_train_pi.index)
X_valid_pi_scaled = pd.DataFrame(X_valid_pi_scaled, columns=X_valid_pi.columns, index=X_valid_pi.index)
X_test_pi_scaled = pd.DataFrame(X_test_pi_scaled, columns=X_test_pi.columns, index=X_test_pi.index)

In [45]:
lasso_pi_results = train_lasso_model(X_train_pi_scaled, y_train, X_valid_pi_scaled, y_valid, alpha=0.0001)

In [46]:
y_train_pred_all = lasso_results['model'].predict(X_train_scaled)
y_val_pred_all = lasso_results['model'].predict(X_valid_scaled)
y_test_pred_all = lasso_results['model'].predict(X_test_scaled)

train_rmse_all = np.sqrt(mean_squared_error(y_train, y_train_pred_all))
val_rmse_all = np.sqrt(mean_squared_error(y_valid, y_val_pred_all))
test_rmse_all = np.sqrt(mean_squared_error(y_test, y_test_pred_all))

train_r2_all = r2_score(y_train, y_train_pred_all)
val_r2_all = r2_score(y_valid, y_val_pred_all)
test_r2_all = r2_score(y_test, y_test_pred_all)

train_mae_all = mean_absolute_error(y_train, y_train_pred_all)
val_mae_all = mean_absolute_error(y_valid, y_val_pred_all)
test_mae_all = mean_absolute_error(y_test, y_test_pred_all)

y_train_pred_top10 = lasso_top10_results['model'].predict(X_train_top10_scaled)
y_val_pred_top10 = lasso_top10_results['model'].predict(X_valid_top10_scaled)
y_test_pred_top10 = lasso_top10_results['model'].predict(X_test_top10_scaled)

train_rmse_top10 = np.sqrt(mean_squared_error(y_train, y_train_pred_top10))
val_rmse_top10 = np.sqrt(mean_squared_error(y_valid, y_val_pred_top10))
test_rmse_top10 = np.sqrt(mean_squared_error(y_test, y_test_pred_top10))

train_r2_top10 = r2_score(y_train, y_train_pred_top10)
val_r2_top10 = r2_score(y_valid, y_val_pred_top10)
test_r2_top10 = r2_score(y_test, y_test_pred_top10)

train_mae_top10 = mean_absolute_error(y_train, y_train_pred_top10)
val_mae_top10 = mean_absolute_error(y_valid, y_val_pred_top10)
test_mae_top10 = mean_absolute_error(y_test, y_test_pred_top10)

y_train_pred_corr = lasso_corr_results['model'].predict(X_train_corr_scaled)
y_val_pred_corr = lasso_corr_results['model'].predict(X_valid_corr_scaled)
y_test_pred_corr = lasso_corr_results['model'].predict(X_test_corr_scaled)

train_rmse_corr = np.sqrt(mean_squared_error(y_train, y_train_pred_corr))
val_rmse_corr = np.sqrt(mean_squared_error(y_valid, y_val_pred_corr))
test_rmse_corr = np.sqrt(mean_squared_error(y_test, y_test_pred_corr))

train_r2_corr = r2_score(y_train, y_train_pred_corr)
val_r2_corr = r2_score(y_valid, y_val_pred_corr)
test_r2_corr = r2_score(y_test, y_test_pred_corr)

train_mae_corr = mean_absolute_error(y_train, y_train_pred_corr)
val_mae_corr = mean_absolute_error(y_valid, y_val_pred_corr)
test_mae_corr = mean_absolute_error(y_test, y_test_pred_corr)

y_train_pred_pi = lasso_pi_results['model'].predict(X_train_pi_scaled)
y_val_pred_pi = lasso_pi_results['model'].predict(X_valid_pi_scaled)
y_test_pred_pi = lasso_pi_results['model'].predict(X_test_pi_scaled)

train_rmse_pi = np.sqrt(mean_squared_error(y_train, y_train_pred_pi))
val_rmse_pi = np.sqrt(mean_squared_error(y_valid, y_val_pred_pi))
test_rmse_pi = np.sqrt(mean_squared_error(y_test, y_test_pred_pi))

train_r2_pi = r2_score(y_train, y_train_pred_pi)
val_r2_pi = r2_score(y_valid, y_val_pred_pi)
test_r2_pi = r2_score(y_test, y_test_pred_pi)

train_mae_pi = mean_absolute_error(y_train, y_train_pred_pi)
val_mae_pi = mean_absolute_error(y_valid, y_val_pred_pi)
test_mae_pi = mean_absolute_error(y_test, y_test_pred_pi)

stability_pi = measure_stability(Lasso(alpha=0.0001, random_state=42, max_iter=10000), X_train_pi_scaled, y_train)

comparison_df = pd.DataFrame({
    'Метрика': [
        'RMSE (Train)',
        'RMSE (Validation)',
        'RMSE (Test)',
        'R² (Train)',
        'R² (Validation)',
        'R² (Test)',
        'MAE (Train)',
        'MAE (Validation)',
        'MAE (Test)',
        'Время обучения (сек)',
        'Стабильность RMSE (std)',
        'Стабильность R² (std)'
    ],
    'Все признаки': [
        f"{train_rmse_all:.2f}",
        f"{val_rmse_all:.2f}",
        f"{test_rmse_all:.2f}",
        f"{train_r2_all:.4f}",
        f"{val_r2_all:.4f}",
        f"{test_r2_all:.4f}",
        f"{train_mae_all:.2f}",
        f"{val_mae_all:.2f}",
        f"{test_mae_all:.2f}",
        f"{lasso_results['time_training']:.4f}",
        f"{stability_all['rmse_std']:.4f}",
        f"{stability_all['r2_std']:.4f}"
    ],
    'Топ-10 признаков': [
        f"{train_rmse_top10:.2f}",
        f"{val_rmse_top10:.2f}",
        f"{test_rmse_top10:.2f}",
        f"{train_r2_top10:.4f}",
        f"{val_r2_top10:.4f}",
        f"{test_r2_top10:.4f}",
        f"{train_mae_top10:.2f}",
        f"{val_mae_top10:.2f}",
        f"{test_mae_top10:.2f}",
        f"{lasso_top10_results['time_training']:.4f}",
        f"{stability_top10['rmse_std']:.4f}",
        f"{stability_top10['r2_std']:.4f}"
    ],
    'Топ-10 corr': [
        f"{train_rmse_corr:.2f}",
        f"{val_rmse_corr:.2f}",
        f"{test_rmse_corr:.2f}",
        f"{train_r2_corr:.4f}",
        f"{val_r2_corr:.4f}",
        f"{test_r2_corr:.4f}",
        f"{train_mae_corr:.2f}",
        f"{val_mae_corr:.2f}",
        f"{test_mae_corr:.2f}",
        f"{lasso_corr_results['time_training']:.4f}",
        f"{stability_corr['rmse_std']:.4f}",
        f"{stability_corr['r2_std']:.4f}"
    ],
    'Топ-10 PI': [
        f"{train_rmse_pi:.2f}",
        f"{val_rmse_pi:.2f}",
        f"{test_rmse_pi:.2f}",
        f"{train_r2_pi:.4f}",
        f"{val_r2_pi:.4f}",
        f"{test_r2_pi:.4f}",
        f"{train_mae_pi:.2f}",
        f"{val_mae_pi:.2f}",
        f"{test_mae_pi:.2f}",
        f"{lasso_pi_results['time_training']:.4f}",
        f"{stability_pi['rmse_std']:.4f}",
        f"{stability_pi['r2_std']:.4f}"
    ]
})

print(comparison_df.to_string(index=False))

                Метрика Все признаки Топ-10 признаков Топ-10 corr Топ-10 PI
           RMSE (Train)      1030.20          1044.19     1044.68   1042.28
      RMSE (Validation)      1034.07          1047.25     1049.83   1044.57
            RMSE (Test)      1039.50          1055.87     1056.88   1049.59
             R² (Train)       0.5860           0.5747      0.5743    0.5763
        R² (Validation)       0.5788           0.5680      0.5659    0.5702
              R² (Test)       0.5733           0.5597      0.5589    0.5649
            MAE (Train)       707.39           717.53      720.16    717.29
       MAE (Validation)       709.62           718.04      722.45    718.07
             MAE (Test)       710.36           723.44      726.59    721.67
   Время обучения (сек)       0.0089           0.0046      0.0026    0.0031
Стабильность RMSE (std)      40.6445          41.5275     25.4389   25.4148
  Стабильность R² (std)       0.0326           0.0340      0.0166    0.0162

Отбираем признаки по модели Shap и снова обучаем моодель Lasso:

In [47]:
def select_features_shap(X, y, top_k=10, random_state=42, sample_size=100):
    X_selected_shap = X.copy()
    X_train_shap, X_temp_shap, y_train_shap, y_temp_shap = train_test_split(X_selected_shap, y, test_size=0.3, random_state=random_state)
    X_val_shap, X_test_shap, y_val_shap, y_test_shap = train_test_split(X_temp_shap, y_temp_shap, test_size=0.5, random_state=random_state)
    
    scaler_shap = MinMaxScaler()
    X_train_shap_scaled = scaler_shap.fit_transform(X_train_shap)
    X_val_shap_scaled = scaler_shap.transform(X_val_shap)
    
    lasso_for_shap = Lasso(alpha=0.001, random_state=random_state, max_iter=10000)
    lasso_for_shap.fit(X_train_shap_scaled, y_train_shap)
    
    explainer_shap = shap.LinearExplainer(lasso_for_shap, X_train_shap_scaled)
    
    if len(X_val_shap_scaled) > sample_size:
        shap_sample = X_val_shap_scaled[:sample_size]
        print(f"Используем подвыборку из {sample_size} образцов для SHAP")
    else:
        shap_sample = X_val_shap_scaled
        print(f"Используем все {len(X_val_shap_scaled)} образцов для SHAP")
    
    shap_values = explainer_shap.shap_values(shap_sample)
    shap_importance = np.abs(shap_values).mean(axis=0)
    
    importance_df = pd.DataFrame({
        'Признак': X_selected_shap.columns,
        'SHAP_важность': shap_importance
    }).sort_values('SHAP_важность', ascending=False)
    
    top_features_shap = importance_df.head(top_k)['Признак'].tolist()
    X_selected_shap = X_selected_shap[top_features_shap]
    
    # Выводим результаты
    print(f"\nТОП-{top_k} ПРИЗНАКОВ ПО SHAP IMPORTANCE (Lasso):")
    display_df = importance_df.head(top_k).copy()
    display_df['SHAP_важность'] = display_df['SHAP_важность'].round(4)
    print(display_df.to_string(index=False))
    
    print(f"\nИтоговое количество признаков: {X_selected_shap.shape[1]}")
    
    return X_selected_shap, top_features_shap, importance_df, shap_values

In [48]:
X_selected_shap, top_features_shap, importance_df, shap_values = select_features_shap(X_numeric, y, top_k=10,random_state=42)

Background dataset has 33865 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=33865 when initializing the masker.

Используем подвыборку из 100 образцов для SHAP

ТОП-10 ПРИЗНАКОВ ПО SHAP IMPORTANCE (Lasso):
          Признак  SHAP_важность
        bathrooms       471.5250
         bedrooms       436.1191
          Doorman       302.4316
    LaundryinUnit       143.3235
         Elevator       109.0306
LaundryinBuilding        96.9507
    FitnessCenter        81.3897
      DogsAllowed        77.5434
   HardwoodFloors        72.6420
       Dishwasher        69.9573

Итоговое количество признаков: 10

In [49]:
X_train_shap, X_valid_shap, X_test_shap, y_train, y_valid, y_test = splitter.train_valid_test_random_split(X_selected_shap, y, validation_size=0.2, test_size=0.2)

Обучающая выборка: 29027 объектов
Валидационная выборка: 9676 объектов
Тестовая выборка: 9676 объектов

In [50]:
scaler_shap = MinMaxScaler()
X_train_shap_scaled = scaler_shap.fit_transform(X_train_shap)
X_valid_shap_scaled = scaler_shap.transform(X_valid_shap)
X_test_shap_scaled = scaler_shap.transform(X_test_shap)

X_train_shap_scaled = pd.DataFrame(X_train_shap_scaled, columns=X_train_shap.columns, index=X_train_shap.index)
X_valid_shap_scaled = pd.DataFrame(X_valid_shap_scaled, columns=X_valid_shap.columns, index=X_valid_shap.index)
X_test_shap_scaled = pd.DataFrame(X_test_shap_scaled, columns=X_test_shap.columns, index=X_test_shap.index)

In [51]:
lasso_shap_results = train_lasso_model(X_train_shap_scaled, y_train, X_valid_shap_scaled, y_valid, alpha=0.0001)

In [52]:
y_train_pred_all = lasso_results['model'].predict(X_train_scaled)
y_val_pred_all = lasso_results['model'].predict(X_valid_scaled)
y_test_pred_all = lasso_results['model'].predict(X_test_scaled)

train_rmse_all = np.sqrt(mean_squared_error(y_train, y_train_pred_all))
val_rmse_all = np.sqrt(mean_squared_error(y_valid, y_val_pred_all))
test_rmse_all = np.sqrt(mean_squared_error(y_test, y_test_pred_all))

train_r2_all = r2_score(y_train, y_train_pred_all)
val_r2_all = r2_score(y_valid, y_val_pred_all)
test_r2_all = r2_score(y_test, y_test_pred_all)

train_mae_all = mean_absolute_error(y_train, y_train_pred_all)
val_mae_all = mean_absolute_error(y_valid, y_val_pred_all)
test_mae_all = mean_absolute_error(y_test, y_test_pred_all)

y_train_pred_top10 = lasso_top10_results['model'].predict(X_train_top10_scaled)
y_val_pred_top10 = lasso_top10_results['model'].predict(X_valid_top10_scaled)
y_test_pred_top10 = lasso_top10_results['model'].predict(X_test_top10_scaled)

train_rmse_top10 = np.sqrt(mean_squared_error(y_train, y_train_pred_top10))
val_rmse_top10 = np.sqrt(mean_squared_error(y_valid, y_val_pred_top10))
test_rmse_top10 = np.sqrt(mean_squared_error(y_test, y_test_pred_top10))

train_r2_top10 = r2_score(y_train, y_train_pred_top10)
val_r2_top10 = r2_score(y_valid, y_val_pred_top10)
test_r2_top10 = r2_score(y_test, y_test_pred_top10)

train_mae_top10 = mean_absolute_error(y_train, y_train_pred_top10)
val_mae_top10 = mean_absolute_error(y_valid, y_val_pred_top10)
test_mae_top10 = mean_absolute_error(y_test, y_test_pred_top10)

y_train_pred_corr = lasso_corr_results['model'].predict(X_train_corr_scaled)
y_val_pred_corr = lasso_corr_results['model'].predict(X_valid_corr_scaled)
y_test_pred_corr = lasso_corr_results['model'].predict(X_test_corr_scaled)

train_rmse_corr = np.sqrt(mean_squared_error(y_train, y_train_pred_corr))
val_rmse_corr = np.sqrt(mean_squared_error(y_valid, y_val_pred_corr))
test_rmse_corr = np.sqrt(mean_squared_error(y_test, y_test_pred_corr))

train_r2_corr = r2_score(y_train, y_train_pred_corr)
val_r2_corr = r2_score(y_valid, y_val_pred_corr)
test_r2_corr = r2_score(y_test, y_test_pred_corr)

train_mae_corr = mean_absolute_error(y_train, y_train_pred_corr)
val_mae_corr = mean_absolute_error(y_valid, y_val_pred_corr)
test_mae_corr = mean_absolute_error(y_test, y_test_pred_corr)

y_train_pred_pi = lasso_pi_results['model'].predict(X_train_pi_scaled)
y_val_pred_pi = lasso_pi_results['model'].predict(X_valid_pi_scaled)
y_test_pred_pi = lasso_pi_results['model'].predict(X_test_pi_scaled)

train_rmse_pi = np.sqrt(mean_squared_error(y_train, y_train_pred_pi))
val_rmse_pi = np.sqrt(mean_squared_error(y_valid, y_val_pred_pi))
test_rmse_pi = np.sqrt(mean_squared_error(y_test, y_test_pred_pi))

train_r2_pi = r2_score(y_train, y_train_pred_pi)
val_r2_pi = r2_score(y_valid, y_val_pred_pi)
test_r2_pi = r2_score(y_test, y_test_pred_pi)

train_mae_pi = mean_absolute_error(y_train, y_train_pred_pi)
val_mae_pi = mean_absolute_error(y_valid, y_val_pred_pi)
test_mae_pi = mean_absolute_error(y_test, y_test_pred_pi)

y_train_pred_shap = lasso_shap_results['model'].predict(X_train_shap_scaled)
y_val_pred_shap = lasso_shap_results['model'].predict(X_valid_shap_scaled)
y_test_pred_shap = lasso_shap_results['model'].predict(X_test_shap_scaled)

train_rmse_shap = np.sqrt(mean_squared_error(y_train, y_train_pred_shap))
val_rmse_shap = np.sqrt(mean_squared_error(y_valid, y_val_pred_shap))
test_rmse_shap = np.sqrt(mean_squared_error(y_test, y_test_pred_shap))

train_r2_shap = r2_score(y_train, y_train_pred_shap)
val_r2_shap = r2_score(y_valid, y_val_pred_shap)
test_r2_shap = r2_score(y_test, y_test_pred_shap)

train_mae_shap = mean_absolute_error(y_train, y_train_pred_shap)
val_mae_shap = mean_absolute_error(y_valid, y_val_pred_shap)
test_mae_shap = mean_absolute_error(y_test, y_test_pred_shap)

stability_shap = measure_stability(Lasso(alpha=0.0001, random_state=42, max_iter=10000), X_train_shap_scaled, y_train)

comparison_df = pd.DataFrame({
    'Метрика': [
        'RMSE (Train)',
        'RMSE (Validation)',
        'RMSE (Test)',
        'R² (Train)',
        'R² (Validation)',
        'R² (Test)',
        'MAE (Train)',
        'MAE (Validation)',
        'MAE (Test)',
        'Время обучения (сек)',
        'Стабильность RMSE (std)',
        'Стабильность R² (std)'
    ],
    'Все признаки': [
        f"{train_rmse_all:.2f}",
        f"{val_rmse_all:.2f}",
        f"{test_rmse_all:.2f}",
        f"{train_r2_all:.4f}",
        f"{val_r2_all:.4f}",
        f"{test_r2_all:.4f}",
        f"{train_mae_all:.2f}",
        f"{val_mae_all:.2f}",
        f"{test_mae_all:.2f}",
        f"{lasso_results['time_training']:.4f}",
        f"{stability_all['rmse_std']:.4f}",
        f"{stability_all['r2_std']:.4f}"
    ],
    'Топ-10': [
        f"{train_rmse_top10:.2f}",
        f"{val_rmse_top10:.2f}",
        f"{test_rmse_top10:.2f}",
        f"{train_r2_top10:.4f}",
        f"{val_r2_top10:.4f}",
        f"{test_r2_top10:.4f}",
        f"{train_mae_top10:.2f}",
        f"{val_mae_top10:.2f}",
        f"{test_mae_top10:.2f}",
        f"{lasso_top10_results['time_training']:.4f}",
        f"{stability_top10['rmse_std']:.4f}",
        f"{stability_top10['r2_std']:.4f}"
    ],
    'Топ-10 corr': [
        f"{train_rmse_corr:.2f}",
        f"{val_rmse_corr:.2f}",
        f"{test_rmse_corr:.2f}",
        f"{train_r2_corr:.4f}",
        f"{val_r2_corr:.4f}",
        f"{test_r2_corr:.4f}",
        f"{train_mae_corr:.2f}",
        f"{val_mae_corr:.2f}",
        f"{test_mae_corr:.2f}",
        f"{lasso_corr_results['time_training']:.4f}",
        f"{stability_corr['rmse_std']:.4f}",
        f"{stability_corr['r2_std']:.4f}"
    ],
    'Топ-10 PI': [
        f"{train_rmse_pi:.2f}",
        f"{val_rmse_pi:.2f}",
        f"{test_rmse_pi:.2f}",
        f"{train_r2_pi:.4f}",
        f"{val_r2_pi:.4f}",
        f"{test_r2_pi:.4f}",
        f"{train_mae_pi:.2f}",
        f"{val_mae_pi:.2f}",
        f"{test_mae_pi:.2f}",
        f"{lasso_pi_results['time_training']:.4f}",
        f"{stability_pi['rmse_std']:.4f}",
        f"{stability_pi['r2_std']:.4f}"
    ],
    'Топ-10 SHAP': [
        f"{train_rmse_shap:.2f}",
        f"{val_rmse_shap:.2f}",
        f"{test_rmse_shap:.2f}",
        f"{train_r2_shap:.4f}",
        f"{val_r2_shap:.4f}",
        f"{test_r2_shap:.4f}",
        f"{train_mae_shap:.2f}",
        f"{val_mae_shap:.2f}",
        f"{test_mae_shap:.2f}",
        f"{lasso_shap_results['time_training']:.4f}",
        f"{stability_shap['rmse_std']:.4f}",
        f"{stability_shap['r2_std']:.4f}"
    ]
})

print(comparison_df.to_string(index=False))

                Метрика Все признаки  Топ-10 Топ-10 corr Топ-10 PI Топ-10 SHAP
           RMSE (Train)      1030.20 1044.19     1044.68   1042.28     1042.84
      RMSE (Validation)      1034.07 1047.25     1049.83   1044.57     1047.95
            RMSE (Test)      1039.50 1055.87     1056.88   1049.59     1051.22
             R² (Train)       0.5860  0.5747      0.5743    0.5763      0.5758
        R² (Validation)       0.5788  0.5680      0.5659    0.5702      0.5674
              R² (Test)       0.5733  0.5597      0.5589    0.5649      0.5636
            MAE (Train)       707.39  717.53      720.16    717.29      716.26
       MAE (Validation)       709.62  718.04      722.45    718.07      719.70
             MAE (Test)       710.36  723.44      726.59    721.67      720.62
   Время обучения (сек)       0.0089  0.0046      0.0026    0.0031      0.0027
Стабильность RMSE (std)      40.6445 41.5275     25.4389   25.4148     25.3345
  Стабильность R² (std)       0.0326  0.0340      0.0166    0.0162      0.0162

***Вывод: Самое лучшее качество модели по метрикам показывает модель с методом отбора топ-10 признаков Permutation importance. Скорость обучения самая быстрая у модели с самыми коррелирующими признаками. Лучшую стабильность показал Shap и также Permutation importance.
Таким образом, Permutation importance показывает наилучший баланс между качеством прогнозирования, скоростью и стабильностью. В данной задаче рекомендуется к применению именно он.***

## 7. Hyperparameter optimization

ElasticNet - это линейная модель регрессии, которая комбинирует два типа регуляризации:

- L1-регуляризация (как в Lasso) - обнуляет неважные признаки
- L2-регуляризация (как в Ridge) - сглаживает коэффициенты

Loss = MSE + α * (l1_ratio * ||w||₁ + (1 - l1_ratio) * ||w||₂²)

- alpha - общая сила регуляризации (чем больше, тем сильнее регуляризация)
- l1_ratio - баланс между L1 и L2:
- l1_ratio = 1 → чистая Lasso
- l1_ratio = 0 → чистая Ridge
- 0 < l1_ratio < 1 → смесь L1 и L2

In [53]:
X_train_elastic, X_valid_elastic, X_test_elastic, y_train, y_valid, y_test = splitter.train_valid_test_random_split(X_selected_pi, y, validation_size=0.2, test_size=0.2)

Обучающая выборка: 29027 объектов
Валидационная выборка: 9676 объектов
Тестовая выборка: 9676 объектов

In [54]:
scaler_elastic = MinMaxScaler()
X_train_elastic_scaled = scaler_elastic.fit_transform(X_train_elastic)
X_valid_elastic_scaled = scaler_elastic.transform(X_valid_elastic)
X_test_elastic_scaled = scaler_elastic.transform(X_test_elastic)

In [55]:
param_grid = {
    'alpha': [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0],
    'l1_ratio': [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
}

param_distributions = {
    'alpha': np.logspace(-4, 1, 30),  
    'l1_ratio': np.linspace(0, 1, 30)
}

grid_search = GridSearchCV(
    estimator=ElasticNet(random_state=42, max_iter=10000),
    param_grid=param_grid,
    cv=5,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    verbose=1
)

grid_search.fit(X_train_elastic_scaled, y_train)

random_search = RandomizedSearchCV(
    estimator=ElasticNet(random_state=42, max_iter=10000),
    param_distributions=param_distributions,
    n_iter=50,
    cv=5,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    verbose=1,
    random_state=42,
    return_train_score=True
)

random_search.fit(X_train_elastic_scaled, y_train)

print(f"\nЛучшие параметры Grid Search: {grid_search.best_params_}")
print(f"Лучший CV score: {grid_search.best_score_:.4f}")
best_rmse_cv_grid = np.sqrt(-grid_search.best_score_)
print(f"Лучший CV RMSE: {best_rmse_cv_grid:.4f}")


print(f"Лучшие параметры Random Search: {random_search.best_params_}")
print(f"Лучший CV score: {random_search.best_score_:.4f}")
best_rmse_cv_random = np.sqrt(-random_search.best_score_)
print(f"Лучший CV RMSE: {best_rmse_cv_random:.4f}")

Fitting 5 folds for each of 66 candidates, totalling 330 fits
Fitting 5 folds for each of 50 candidates, totalling 250 fits

Лучшие параметры Grid Search: {'alpha': 0.01, 'l1_ratio': 1.0}
Лучший CV score: -1088128.7308
Лучший CV RMSE: 1043.1341
Лучшие параметры Random Search: {'l1_ratio': np.float64(1.0), 'alpha': np.float64(0.003562247890262444)}
Лучший CV score: -1088128.8738
Лучший CV RMSE: 1043.1342

In [56]:
y_valid_pred_grid = grid_search.best_estimator_.predict(X_valid_elastic_scaled)
valid_rmse_grid = np.sqrt(mean_squared_error(y_valid, y_valid_pred_grid))
valid_r2_grid = r2_score(y_valid, y_valid_pred_grid)

y_valid_pred_random = random_search.best_estimator_.predict(X_valid_elastic_scaled)
valid_rmse_random = np.sqrt(mean_squared_error(y_valid, y_valid_pred_random))
valid_r2_random = r2_score(y_valid, y_valid_pred_random)

y_test_pred_grid = grid_search.best_estimator_.predict(X_test_elastic_scaled)
test_rmse_grid = np.sqrt(mean_squared_error(y_test, y_test_pred_grid))
test_r2_grid = r2_score(y_test, y_test_pred_grid)

y_test_pred_random = random_search.best_estimator_.predict(X_test_elastic_scaled)
test_rmse_random = np.sqrt(mean_squared_error(y_test, y_test_pred_random))
test_r2_random = r2_score(y_test, y_test_pred_random)

if valid_rmse_grid < valid_rmse_random:
    best_method = "Grid Search"
    best_model = grid_search.best_estimator_
    best_params = grid_search.best_params_
    best_test_rmse = test_rmse_grid
    best_test_r2 = test_r2_grid
else:
    best_method = "Random Search"
    best_model = random_search.best_estimator_
    best_params = random_search.best_params_
    best_test_rmse = test_rmse_random
    best_test_r2 = test_r2_random

print(f"ЛУЧШАЯ МОДЕЛЬ: {best_method}")
print(f"Наилучший гиперпараметр alpha = {best_params['alpha']:.4f}")
print(f"Наилучший гиперпараметр l1_ratio = {best_params['l1_ratio']:.1f}")
print(f"Test RMSE = {best_test_rmse:.4f}")
print(f"Test R² = {best_test_r2:.4f}")

ЛУЧШАЯ МОДЕЛЬ: Random Search
Наилучший гиперпараметр alpha = 0.0036
Наилучший гиперпараметр l1_ratio = 1.0
Test RMSE = 1049.5940
Test R² = 0.5649

In [57]:
best_elasticnet = ElasticNet(alpha=0.0036,l1_ratio=1.0,random_state=42,max_iter=50000, tol=0.0001)
best_elasticnet.fit(X_train_scaled, y_train)

y_train_pred = best_elasticnet.predict(X_train_scaled)
y_valid_pred = best_elasticnet.predict(X_valid_scaled)
y_test_pred = best_elasticnet.predict(X_test_scaled)

train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
train_r2 = r2_score(y_train, y_train_pred)
train_mae = mean_absolute_error(y_train, y_train_pred)

valid_rmse = np.sqrt(mean_squared_error(y_valid, y_valid_pred))
valid_r2 = r2_score(y_valid, y_valid_pred)
valid_mae = mean_absolute_error(y_valid, y_valid_pred)

test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))
test_r2 = r2_score(y_test, y_test_pred)
test_mae = mean_absolute_error(y_test, y_test_pred)

results_df = pd.DataFrame({
    'Выборка': ['Train', 'Valid', 'Test'],
    'RMSE': [train_rmse, valid_rmse, test_rmse],
    'R²': [train_r2, valid_r2, test_r2],
    'MAE': [train_mae, valid_mae, test_mae]
})

print("\n" + results_df.to_string(index=False))

Выборка        RMSE       R²        MAE
  Train 1030.204520 0.586041 707.445052
  Valid 1034.133097 0.578735 709.699191
   Test 1039.548350 0.573232 710.426939

Ищем гиперпараметры с Optuna и снова обучаем ElasticNet

In [58]:
def objective(trial):
    alpha = trial.suggest_float('alpha', 1e-5, 1e1, log=True)
    l1_ratio = trial.suggest_float('l1_ratio', 0.0, 1.0)
    max_iter = trial.suggest_int('max_iter', 10000, 50000, step=5000)
    tol = trial.suggest_float('tol', 1e-5, 1e-3, log=True)
    
    model = ElasticNet(
        alpha=alpha,
        l1_ratio=l1_ratio,
        max_iter=max_iter,
        tol=tol,
        random_state=42
    )
    
    cv_scores = -cross_val_score(
        model, 
        X_train_scaled, 
        y_train, 
        cv=5,
        scoring='neg_root_mean_squared_error',
        n_jobs=-1
    )
    
    return np.mean(cv_scores)

In [59]:
study = optuna.create_study(
    direction='minimize',
    study_name='elasticnet_optimization',
    storage=None, 
    sampler=optuna.samplers.TPESampler(seed=42),
    pruner=optuna.pruners.MedianPruner()
)

n_trials = 100 
print(f"Количество итераций: {n_trials}")
print("Поиск начался... (может занять несколько минут)")

study.optimize(objective, n_trials=n_trials, show_progress_bar=False)

[I 2026-07-07 13:28:02,893] A new study created in memory with name: elasticnet_optimization
[I 2026-07-07 13:28:03,037] Trial 0 finished with value: 1032.5199344989421 and parameters: {'alpha': 0.0017670169402947942, 'l1_ratio': 0.9507143064099162, 'max_iter': 40000, 'tol': 0.00015751320499779721}. Best is trial 0 with value: 1032.5199344989421.

Количество итераций: 100
Поиск начался... (может занять несколько минут)

[I 2026-07-07 13:28:03,076] Trial 1 finished with value: 1032.356913416511 and parameters: {'alpha': 8.632008168602535e-05, 'l1_ratio': 0.15599452033620265, 'max_iter': 10000, 'tol': 0.0005399484409787432}. Best is trial 1 with value: 1032.356913416511.
[I 2026-07-07 13:28:03,206] Trial 2 finished with value: 1194.4707390415492 and parameters: {'alpha': 0.040428727350273294, 'l1_ratio': 0.7080725777960455, 'max_iter': 10000, 'tol': 0.0008706020878304854}. Best is trial 1 with value: 1032.356913416511.
[I 2026-07-07 13:28:03,337] Trial 3 finished with value: 1514.0453604638992 and parameters: {'alpha': 0.9877700294007905, 'l1_ratio': 0.21233911067827616, 'max_iter': 15000, 'tol': 2.3270677083837777e-05}. Best is trial 1 with value: 1032.356913416511.
[I 2026-07-07 13:28:03,482] Trial 4 finished with value: 1037.2033485851655 and parameters: {'alpha': 0.0006690421166498799, 'l1_ratio': 0.5247564316322378, 'max_iter': 25000, 'tol': 3.8234752246751835e-05}. Best is trial 1 with value: 1032.356913416511.
[I 2026-07-07 13:28:03,613] Trial 5 finished with value: 1311.0851233704977 and parameters: {'alpha': 0.046894009635376876, 'l1_ratio': 0.13949386065204183, 'max_iter': 20000, 'tol': 5.4041038546473305e-05}. Best is trial 1 with value: 1032.356913416511.
[I 2026-07-07 13:28:03,756] Trial 6 finished with value: 1063.5727741899773 and parameters: {'alpha': 0.0054502936945582505, 'l1_ratio': 0.7851759613930136, 'max_iter': 15000, 'tol': 0.00010677482709481354}. Best is trial 1 with value: 1032.356913416511.
[I 2026-07-07 13:28:03,885] Trial 7 finished with value: 1294.5264638776187 and parameters: {'alpha': 0.035849855803404725, 'l1_ratio': 0.046450412719997725, 'max_iter': 35000, 'tol': 2.1930485556643678e-05}. Best is trial 1 with value: 1032.356913416511.
[I 2026-07-07 13:28:04,040] Trial 8 finished with value: 1033.7899251471015 and parameters: {'alpha': 2.4564592152507503e-05, 'l1_ratio': 0.9488855372533332, 'max_iter': 50000, 'tol': 0.0004138040112561013}. Best is trial 1 with value: 1032.356913416511.
[I 2026-07-07 13:28:04,185] Trial 9 finished with value: 1045.8571907055161 and parameters: {'alpha': 0.0006724850206557243, 'l1_ratio': 0.09767211400638387, 'max_iter': 40000, 'tol': 7.591104805282687e-05}. Best is trial 1 with value: 1032.356913416511.
[I 2026-07-07 13:28:04,318] Trial 10 finished with value: 1565.889303721687 and parameters: {'alpha': 5.129141755547034, 'l1_ratio': 0.363727673621631, 'max_iter': 30000, 'tol': 1.0862348973937116e-05}. Best is trial 1 with value: 1032.356913416511.
[I 2026-07-07 13:28:04,467] Trial 11 finished with value: 1031.7637097582235 and parameters: {'alpha': 1.7069998885099803e-05, 'l1_ratio': 0.47844527698200534, 'max_iter': 50000, 'tol': 0.00025131757620929787}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:04,621] Trial 12 finished with value: 1031.764377585028 and parameters: {'alpha': 1.5344412336334914e-05, 'l1_ratio': 0.3796042434202234, 'max_iter': 50000, 'tol': 0.0002724513662703497}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:04,770] Trial 13 finished with value: 1031.783901275167 and parameters: {'alpha': 1.2124726943401321e-05, 'l1_ratio': 0.43435627175641134, 'max_iter': 50000, 'tol': 0.00024653599281707783}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:04,914] Trial 14 finished with value: 1032.040042104532 and parameters: {'alpha': 9.61293438008881e-05, 'l1_ratio': 0.5916836359300597, 'max_iter': 45000, 'tol': 0.0002737858405457551}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:04,969] Trial 15 finished with value: 1032.2720020713164 and parameters: {'alpha': 9.360802561068057e-05, 'l1_ratio': 0.30994896491563173, 'max_iter': 50000, 'tol': 0.00020200513082957767}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:05,116] Trial 16 finished with value: 1031.8382256862692 and parameters: {'alpha': 1.244193297561365e-05, 'l1_ratio': 0.5581369070277538, 'max_iter': 45000, 'tol': 0.0009818226878189108}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:05,266] Trial 17 finished with value: 1032.6121375994858 and parameters: {'alpha': 0.00013341227457101728, 'l1_ratio': 0.28876248649855873, 'max_iter': 45000, 'tol': 0.0003921123340166013}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:05,423] Trial 18 finished with value: 1031.864924925628 and parameters: {'alpha': 3.734609889937773e-05, 'l1_ratio': 0.46056344991259746, 'max_iter': 40000, 'tol': 0.00010073712831698305}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:05,572] Trial 19 finished with value: 1037.1844082546559 and parameters: {'alpha': 0.0009340048022110221, 'l1_ratio': 0.6603606759790203, 'max_iter': 35000, 'tol': 0.00013334943673915645}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:05,719] Trial 20 finished with value: 1033.756959767427 and parameters: {'alpha': 0.0002936740138744948, 'l1_ratio': 0.4278980466807257, 'max_iter': 50000, 'tol': 0.0005850369606010752}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:05,878] Trial 21 finished with value: 1031.7668794511242 and parameters: {'alpha': 1.3775266586969277e-05, 'l1_ratio': 0.41619444546785167, 'max_iter': 50000, 'tol': 0.00023733002868285438}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:06,036] Trial 22 finished with value: 1031.7717475738696 and parameters: {'alpha': 1.163952173050834e-05, 'l1_ratio': 0.351521658133212, 'max_iter': 45000, 'tol': 0.0002689476635688829}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:06,195] Trial 23 finished with value: 1031.9698502034375 and parameters: {'alpha': 4.127521929950513e-05, 'l1_ratio': 0.24353220724895053, 'max_iter': 50000, 'tol': 0.00017564841795668959}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:06,351] Trial 24 finished with value: 1031.8632687231275 and parameters: {'alpha': 3.9501715529173265e-05, 'l1_ratio': 0.49409483361788464, 'max_iter': 45000, 'tol': 0.0003176833633643913}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:06,496] Trial 25 finished with value: 1033.33508172441 and parameters: {'alpha': 0.0002357710072866361, 'l1_ratio': 0.38876919478638616, 'max_iter': 50000, 'tol': 0.00038934531148917}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:06,539] Trial 26 finished with value: 1032.0622885434504 and parameters: {'alpha': 1.0321694573594125e-05, 'l1_ratio': 0.6438213784070337, 'max_iter': 40000, 'tol': 0.0006182361547769498}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:06,684] Trial 27 finished with value: 1031.770172855274 and parameters: {'alpha': 4.130028200415547e-05, 'l1_ratio': 0.8139937055778315, 'max_iter': 45000, 'tol': 0.0002051765361791101}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:06,825] Trial 28 finished with value: 1033.529729795907 and parameters: {'alpha': 0.0002065704093529476, 'l1_ratio': 0.24747657885864055, 'max_iter': 35000, 'tol': 0.00011809116334268643}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:06,961] Trial 29 finished with value: 1053.834459916345 and parameters: {'alpha': 0.0020946783868014238, 'l1_ratio': 0.5915176709957256, 'max_iter': 40000, 'tol': 0.00015836433151054317}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:07,107] Trial 30 finished with value: 1081.239278588247 and parameters: {'alpha': 0.0037073998590532783, 'l1_ratio': 0.5075427178876663, 'max_iter': 50000, 'tol': 6.337711639952183e-05}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:07,257] Trial 31 finished with value: 1032.017369630028 and parameters: {'alpha': 2.9603519011837798e-05, 'l1_ratio': 0.8683126536166355, 'max_iter': 45000, 'tol': 0.00020065678328111956}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:07,403] Trial 32 finished with value: 1031.8099245924916 and parameters: {'alpha': 6.0064709510117846e-05, 'l1_ratio': 0.7512467107130207, 'max_iter': 45000, 'tol': 0.00022606227275033565}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:07,563] Trial 33 finished with value: 1034.8612762382406 and parameters: {'alpha': 2.1115969474502017e-05, 'l1_ratio': 0.9608648456740833, 'max_iter': 50000, 'tol': 0.0004550613067025509}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:07,705] Trial 34 finished with value: 1031.7641957688866 and parameters: {'alpha': 6.801733888835287e-05, 'l1_ratio': 0.8731424285218721, 'max_iter': 40000, 'tol': 0.0007354685778697234}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:07,851] Trial 35 finished with value: 1034.5162427869807 and parameters: {'alpha': 0.0002540209647723235, 'l1_ratio': 0.18801187736787173, 'max_iter': 30000, 'tol': 0.0007759099675998481}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:07,992] Trial 36 finished with value: 1032.1427627063106 and parameters: {'alpha': 8.641906773134186e-05, 'l1_ratio': 0.41060355139250354, 'max_iter': 40000, 'tol': 0.0006927588163348708}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:08,150] Trial 37 finished with value: 1032.6519071397706 and parameters: {'alpha': 2.0704723050360772e-05, 'l1_ratio': 0.8926857100816777, 'max_iter': 30000, 'tol': 0.0003377058682760738}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:08,191] Trial 38 finished with value: 1037.572896679239 and parameters: {'alpha': 0.0004841317710205613, 'l1_ratio': 0.31472483121086625, 'max_iter': 35000, 'tol': 0.00046495942670390006}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:08,338] Trial 39 finished with value: 1033.4568038175946 and parameters: {'alpha': 0.00015575031894046672, 'l1_ratio': 0.028737218602766346, 'max_iter': 40000, 'tol': 0.00014429236793551002}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:08,483] Trial 40 finished with value: 1031.8449102914878 and parameters: {'alpha': 6.969643052991264e-05, 'l1_ratio': 0.7386483514716582, 'max_iter': 25000, 'tol': 0.0005303597203264023}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:08,642] Trial 41 finished with value: 1032.431247748563 and parameters: {'alpha': 1.937669289880702e-05, 'l1_ratio': 0.8663510873041204, 'max_iter': 45000, 'tol': 8.575642954471635e-05}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:08,788] Trial 42 finished with value: 1031.7781384964437 and parameters: {'alpha': 5.85959781410958e-05, 'l1_ratio': 0.7996359886554028, 'max_iter': 50000, 'tol': 0.00031250677212946333}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:08,935] Trial 43 finished with value: 1031.936180179115 and parameters: {'alpha': 2.4538844299588577e-05, 'l1_ratio': 0.8197928023793245, 'max_iter': 45000, 'tol': 0.00020666971864489843}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:09,070] Trial 44 finished with value: 1338.2396314532864 and parameters: {'alpha': 0.17196734760326476, 'l1_ratio': 0.6905706614424535, 'max_iter': 50000, 'tol': 4.0114570936876324e-05}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:09,241] Trial 45 finished with value: 1037.7449063725678 and parameters: {'alpha': 1.0040490035517763e-05, 'l1_ratio': 0.9740796098099614, 'max_iter': 10000, 'tol': 0.0002774807491653778}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:09,391] Trial 46 finished with value: 1031.8755265975847 and parameters: {'alpha': 4.9272529633194674e-05, 'l1_ratio': 0.8987225190551236, 'max_iter': 45000, 'tol': 0.00017943931555864057}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:09,535] Trial 47 finished with value: 1033.845266355484 and parameters: {'alpha': 0.0003903500844059301, 'l1_ratio': 0.5575176515728075, 'max_iter': 50000, 'tol': 0.0008974156724600669}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:09,684] Trial 48 finished with value: 1206.9043614672835 and parameters: {'alpha': 0.015618415255431365, 'l1_ratio': 0.12320260120828685, 'max_iter': 40000, 'tol': 0.0003540368332582351}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:09,845] Trial 49 finished with value: 1032.3318835637558 and parameters: {'alpha': 0.00013469158768082714, 'l1_ratio': 0.4768289857990554, 'max_iter': 45000, 'tol': 0.00011883955980444177}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:09,997] Trial 50 finished with value: 1044.757523039035 and parameters: {'alpha': 0.0008981947077772498, 'l1_ratio': 0.362978068885369, 'max_iter': 50000, 'tol': 1.0704401996178624e-05}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:10,145] Trial 51 finished with value: 1031.7753704332024 and parameters: {'alpha': 1.736019762490924e-05, 'l1_ratio': 0.3420403348266169, 'max_iter': 45000, 'tol': 0.00024902164066017973}. Best is trial 11 with value: 1031.7637097582235.
[I 2026-07-07 13:28:10,308] Trial 52 finished with value: 1031.763700963881 and parameters: {'alpha': 1.6436538853545497e-05, 'l1_ratio': 0.4465542465133629, 'max_iter': 40000, 'tol': 0.0002851946426951841}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:10,465] Trial 53 finished with value: 1031.8431734898963 and parameters: {'alpha': 3.3096945240159036e-05, 'l1_ratio': 0.45425141592512097, 'max_iter': 40000, 'tol': 0.00015400271484748818}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:10,624] Trial 54 finished with value: 1032.1726745430635 and parameters: {'alpha': 0.00011421863602472851, 'l1_ratio': 0.5253961837360921, 'max_iter': 35000, 'tol': 0.0004972641094341709}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:10,781] Trial 55 finished with value: 1031.7754113839312 and parameters: {'alpha': 1.5899625116159596e-05, 'l1_ratio': 0.28124725514548865, 'max_iter': 50000, 'tol': 0.0002828588636753867}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:10,926] Trial 56 finished with value: 1031.8098399027192 and parameters: {'alpha': 4.174108808304903e-05, 'l1_ratio': 0.6421024788993669, 'max_iter': 40000, 'tol': 0.00022928410346535825}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:11,067] Trial 57 finished with value: 1031.8326138803359 and parameters: {'alpha': 2.8093952116492547e-05, 'l1_ratio': 0.39234075837140714, 'max_iter': 45000, 'tol': 1.3728725872462924e-05}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:11,215] Trial 58 finished with value: 1031.8768534784754 and parameters: {'alpha': 7.73947730742805e-05, 'l1_ratio': 0.9357409691021893, 'max_iter': 35000, 'tol': 0.00017521205202504253}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:11,364] Trial 59 finished with value: 1031.9803529739443 and parameters: {'alpha': 1.0043685296847327e-05, 'l1_ratio': 0.5903107574002722, 'max_iter': 50000, 'tol': 0.00040596415237062944}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:11,510] Trial 60 finished with value: 1511.4543963477827 and parameters: {'alpha': 3.9026149184775916, 'l1_ratio': 0.8189630099046614, 'max_iter': 45000, 'tol': 0.000100946697581621}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:11,671] Trial 61 finished with value: 1031.7698789211124 and parameters: {'alpha': 1.3507649091841607e-05, 'l1_ratio': 0.42939844206929706, 'max_iter': 15000, 'tol': 0.0002630951464744546}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:11,830] Trial 62 finished with value: 1031.7649716718483 and parameters: {'alpha': 1.7101110450308135e-05, 'l1_ratio': 0.4319782669610104, 'max_iter': 20000, 'tol': 0.0003042525532410814}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:11,976] Trial 63 finished with value: 1031.768826270027 and parameters: {'alpha': 1.4286476450334288e-05, 'l1_ratio': 0.45327353642855445, 'max_iter': 15000, 'tol': 0.00036156514336652964}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:12,136] Trial 64 finished with value: 1031.764047448813 and parameters: {'alpha': 1.7231069051487067e-05, 'l1_ratio': 0.4560117545739776, 'max_iter': 20000, 'tol': 0.00034345410925107887}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:12,178] Trial 65 finished with value: 1031.7650621978564 and parameters: {'alpha': 1.861629613033392e-05, 'l1_ratio': 0.5512426786168666, 'max_iter': 20000, 'tol': 0.0006041578275582562}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:12,317] Trial 66 finished with value: 1031.7852464425127 and parameters: {'alpha': 2.7263122063088207e-05, 'l1_ratio': 0.5402119795576765, 'max_iter': 20000, 'tol': 0.0007857533861295146}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:12,463] Trial 67 finished with value: 1032.0019061356409 and parameters: {'alpha': 5.70554428753772e-05, 'l1_ratio': 0.38890397291795015, 'max_iter': 20000, 'tol': 0.0006323083456795095}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:12,608] Trial 68 finished with value: 1032.5229921496277 and parameters: {'alpha': 0.00017211769562858247, 'l1_ratio': 0.4910909927987592, 'max_iter': 20000, 'tol': 0.0005662243295518264}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:12,764] Trial 69 finished with value: 1031.7973627857468 and parameters: {'alpha': 2.0323229352182752e-05, 'l1_ratio': 0.3231202372254919, 'max_iter': 25000, 'tol': 0.00043284827608815955}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:12,808] Trial 70 finished with value: 1032.3924848654583 and parameters: {'alpha': 0.00010186360501747016, 'l1_ratio': 0.25236229889123996, 'max_iter': 20000, 'tol': 0.0009963725726795083}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:12,949] Trial 71 finished with value: 1031.8570129391087 and parameters: {'alpha': 3.29438318567928e-05, 'l1_ratio': 0.41167705754977313, 'max_iter': 25000, 'tol': 0.00030923364308361144}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:13,095] Trial 72 finished with value: 1031.7673304425214 and parameters: {'alpha': 1.6392780728046416e-05, 'l1_ratio': 0.5130424074933541, 'max_iter': 20000, 'tol': 0.0007085513687507928}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:13,243] Trial 73 finished with value: 1031.9069897105155 and parameters: {'alpha': 4.515087906907472e-05, 'l1_ratio': 0.4599803205459248, 'max_iter': 30000, 'tol': 0.0002338963798890374}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:13,390] Trial 74 finished with value: 1031.8263193375938 and parameters: {'alpha': 2.6578459156678433e-05, 'l1_ratio': 0.379802762285272, 'max_iter': 15000, 'tol': 0.0003646563156441454}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:13,535] Trial 75 finished with value: 1032.0269921657928 and parameters: {'alpha': 1.002929694640797e-05, 'l1_ratio': 0.6162562532118133, 'max_iter': 25000, 'tol': 0.00029929463144275184}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:13,678] Trial 76 finished with value: 1032.073235980563 and parameters: {'alpha': 7.466767736910557e-05, 'l1_ratio': 0.4230108024667213, 'max_iter': 10000, 'tol': 0.0005223754942407379}. Best is trial 52 with value: 1031.763700963881.
[I 2026-07-07 13:28:13,821] Trial 77 finished with value: 1031.7651993534596 and parameters: {'alpha': 1.8690237557199066e-05, 'l1_ratio': 0.47691685598993605, 'max_iter': 25000, 'tol': 0.00018147004364587588}. Best is trial 52 with value: 1031.763700963881.

In [60]:
best_params = study.best_params
best_value = study.best_value

print(f"\nЛУЧШИЕ ГИПЕРПАРАМЕТРЫ Optuna:")
print(f"Наилучший гиперпараметр alpha = {best_params['alpha']:.6f}")
print(f"Наилучший гиперпараметр l1_ratio = {best_params['l1_ratio']:.4f}")
print(f"max_iter = {best_params['max_iter']}")
print(f"tol = {best_params['tol']:.6f}")
print(f"Лучший CV RMSE: {best_value:.4f}")

ЛУЧШИЕ ГИПЕРПАРАМЕТРЫ Optuna:
Наилучший гиперпараметр alpha = 0.000020
Наилучший гиперпараметр l1_ratio = 0.5497
max_iter = 25000
tol = 0.000196
Лучший CV RMSE: 1031.7637

In [61]:
best_model = ElasticNet(alpha=0.00002, l1_ratio=0.5497, max_iter=50000, tol=0.000196,random_state=42)
best_model.fit(X_train_scaled, y_train)

y_train_pred = best_model.predict(X_train_scaled)
y_valid_pred = best_model.predict(X_valid_scaled)
y_test_pred = best_model.predict(X_test_scaled)

train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
valid_rmse = np.sqrt(mean_squared_error(y_valid, y_valid_pred))
test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))

train_r2 = r2_score(y_train, y_train_pred)
valid_r2 = r2_score(y_valid, y_valid_pred)
test_r2 = r2_score(y_test, y_test_pred)

train_mae = mean_absolute_error(y_train, y_train_pred)
valid_mae = mean_absolute_error(y_valid, y_valid_pred)
test_mae = mean_absolute_error(y_test, y_test_pred)

results_df = pd.DataFrame({
    'Выборка': ['Train', 'Valid', 'Test'],
    'RMSE': [train_rmse, valid_rmse, test_rmse],
    'R²': [train_r2, valid_r2, test_r2],
    'MAE': [train_mae, valid_mae, test_mae]
})

print("\n" + results_df.to_string(index=False))

Выборка        RMSE       R²        MAE
  Train 1030.419473 0.585868 708.069762
  Valid 1034.852695 0.578148 710.508294
   Test 1040.069396 0.572804 711.090503

***Вывод: оба метода дали идентичные результаты по метрикам качества модели, несмотря на различия гиперпараметров при подборе. В модели нет признаков переобучения. Модель показывает хорошее качество. Исходя из этого для финальной модели выбираем Optuna, тк это более умный и более стабильный алгоритм поиска.***

In [62]:
def objective_with_cv(trial):
    alpha = trial.suggest_float('alpha', 1e-5, 1e1, log=True)
    l1_ratio = trial.suggest_float('l1_ratio', 0.0, 1.0)
    max_iter = trial.suggest_int('max_iter', 10000, 50000, step=5000)
    tol = trial.suggest_float('tol', 1e-5, 1e-3, log=True)

    model = ElasticNet(alpha=alpha, l1_ratio=l1_ratio, max_iter=max_iter, tol=tol, random_state=42)

    cv = KFold(n_splits=5, shuffle=True, random_state=42)

    cv_scores = -cross_val_score(
        model, 
        X_train_scaled, 
        y_train, 
        cv=cv,
        scoring='neg_root_mean_squared_error',
        n_jobs=-1
    )

    mean_cv_rmse = np.mean(cv_scores)
    trial.set_user_attr('cv_rmse_std', np.std(cv_scores))
    trial.set_user_attr('cv_rmse_min', np.min(cv_scores))
    trial.set_user_attr('cv_rmse_max', np.max(cv_scores))
    
    return mean_cv_rmse

In [63]:
study = optuna.create_study(
    direction='minimize',
    study_name='elasticnet_cv_optimization',
    sampler=optuna.samplers.TPESampler(seed=42),
    pruner=optuna.pruners.MedianPruner(
        n_startup_trials=5,
        n_warmup_steps=10,
        interval_steps=1
    )
)

n_trials = 100
study.optimize(objective_with_cv, n_trials=n_trials, show_progress_bar=False)

[I 2026-07-07 13:28:17,143] A new study created in memory with name: elasticnet_cv_optimization
[I 2026-07-07 13:28:17,285] Trial 0 finished with value: 1032.3681772259063 and parameters: {'alpha': 0.0017670169402947942, 'l1_ratio': 0.9507143064099162, 'max_iter': 40000, 'tol': 0.00015751320499779721}. Best is trial 0 with value: 1032.3681772259063.
[I 2026-07-07 13:28:17,429] Trial 1 finished with value: 1032.2060977980445 and parameters: {'alpha': 8.632008168602535e-05, 'l1_ratio': 0.15599452033620265, 'max_iter': 10000, 'tol': 0.0005399484409787432}. Best is trial 1 with value: 1032.2060977980445.
[I 2026-07-07 13:28:17,574] Trial 2 finished with value: 1194.3020271376154 and parameters: {'alpha': 0.040428727350273294, 'l1_ratio': 0.7080725777960455, 'max_iter': 10000, 'tol': 0.0008706020878304854}. Best is trial 1 with value: 1032.2060977980445.
[I 2026-07-07 13:28:17,706] Trial 3 finished with value: 1513.9520991033332 and parameters: {'alpha': 0.9877700294007905, 'l1_ratio': 0.21233911067827616, 'max_iter': 15000, 'tol': 2.3270677083837777e-05}. Best is trial 1 with value: 1032.2060977980445.
[I 2026-07-07 13:28:17,849] Trial 4 finished with value: 1037.03729610856 and parameters: {'alpha': 0.0006690421166498799, 'l1_ratio': 0.5247564316322378, 'max_iter': 25000, 'tol': 3.8234752246751835e-05}. Best is trial 1 with value: 1032.2060977980445.
[I 2026-07-07 13:28:17,983] Trial 5 finished with value: 1310.9591986653768 and parameters: {'alpha': 0.046894009635376876, 'l1_ratio': 0.13949386065204183, 'max_iter': 20000, 'tol': 5.4041038546473305e-05}. Best is trial 1 with value: 1032.2060977980445.
[I 2026-07-07 13:28:18,124] Trial 6 finished with value: 1063.364471021159 and parameters: {'alpha': 0.0054502936945582505, 'l1_ratio': 0.7851759613930136, 'max_iter': 15000, 'tol': 0.00010677482709481354}. Best is trial 1 with value: 1032.2060977980445.
[I 2026-07-07 13:28:18,255] Trial 7 finished with value: 1294.3975308304246 and parameters: {'alpha': 0.035849855803404725, 'l1_ratio': 0.046450412719997725, 'max_iter': 35000, 'tol': 2.1930485556643678e-05}. Best is trial 1 with value: 1032.2060977980445.
[I 2026-07-07 13:28:18,425] Trial 8 finished with value: 1035.1139998934907 and parameters: {'alpha': 2.4564592152507503e-05, 'l1_ratio': 0.9488855372533332, 'max_iter': 50000, 'tol': 0.0004138040112561013}. Best is trial 1 with value: 1032.2060977980445.
[I 2026-07-07 13:28:18,571] Trial 9 finished with value: 1045.67294222206 and parameters: {'alpha': 0.0006724850206557243, 'l1_ratio': 0.09767211400638387, 'max_iter': 40000, 'tol': 7.591104805282687e-05}. Best is trial 1 with value: 1032.2060977980445.
[I 2026-07-07 13:28:18,601] Trial 10 finished with value: 1565.8032528127083 and parameters: {'alpha': 5.129141755547034, 'l1_ratio': 0.363727673621631, 'max_iter': 30000, 'tol': 1.0862348973937116e-05}. Best is trial 1 with value: 1032.2060977980445.
[I 2026-07-07 13:28:18,748] Trial 11 finished with value: 1031.669728045681 and parameters: {'alpha': 1.7069998885099803e-05, 'l1_ratio': 0.47844527698200534, 'max_iter': 50000, 'tol': 0.00025131757620929787}. Best is trial 11 with value: 1031.669728045681.
[I 2026-07-07 13:28:18,895] Trial 12 finished with value: 1031.6636879279954 and parameters: {'alpha': 1.5344412336334914e-05, 'l1_ratio': 0.3796042434202234, 'max_iter': 50000, 'tol': 0.0002724513662703497}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:19,036] Trial 13 finished with value: 1031.7256977136165 and parameters: {'alpha': 1.2124726943401321e-05, 'l1_ratio': 0.43435627175641134, 'max_iter': 50000, 'tol': 0.00024653599281707783}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:19,186] Trial 14 finished with value: 1031.8927931564454 and parameters: {'alpha': 9.61293438008881e-05, 'l1_ratio': 0.5916836359300597, 'max_iter': 45000, 'tol': 0.0002737858405457551}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:19,337] Trial 15 finished with value: 1032.1217961277732 and parameters: {'alpha': 9.360802561068057e-05, 'l1_ratio': 0.30994896491563173, 'max_iter': 50000, 'tol': 0.00020200513082957767}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:19,501] Trial 16 finished with value: 1031.8268568579786 and parameters: {'alpha': 1.244193297561365e-05, 'l1_ratio': 0.5581369070277538, 'max_iter': 45000, 'tol': 0.0009818226878189108}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:19,646] Trial 17 finished with value: 1032.4599213664317 and parameters: {'alpha': 0.00013341227457101728, 'l1_ratio': 0.28876248649855873, 'max_iter': 45000, 'tol': 0.0003921123340166013}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:19,796] Trial 18 finished with value: 1031.7265959210592 and parameters: {'alpha': 3.734609889937773e-05, 'l1_ratio': 0.46056344991259746, 'max_iter': 40000, 'tol': 0.00010073712831698305}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:19,945] Trial 19 finished with value: 1037.0183953038986 and parameters: {'alpha': 0.0009340048022110221, 'l1_ratio': 0.6603606759790203, 'max_iter': 35000, 'tol': 0.00013334943673915645}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:20,089] Trial 20 finished with value: 1033.6004822822258 and parameters: {'alpha': 0.0002936740138744948, 'l1_ratio': 0.4278980466807257, 'max_iter': 50000, 'tol': 0.0005850369606010752}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:20,244] Trial 21 finished with value: 1031.6848386691104 and parameters: {'alpha': 1.3775266586969277e-05, 'l1_ratio': 0.41619444546785167, 'max_iter': 50000, 'tol': 0.00023733002868285438}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:20,407] Trial 22 finished with value: 1031.6983762001705 and parameters: {'alpha': 1.163952173050834e-05, 'l1_ratio': 0.351521658133212, 'max_iter': 45000, 'tol': 0.0002689476635688829}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:20,564] Trial 23 finished with value: 1031.824636550395 and parameters: {'alpha': 4.127521929950513e-05, 'l1_ratio': 0.24353220724895053, 'max_iter': 50000, 'tol': 0.00017564841795668959}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:20,726] Trial 24 finished with value: 1031.7251238701788 and parameters: {'alpha': 3.9501715529173265e-05, 'l1_ratio': 0.49409483361788464, 'max_iter': 45000, 'tol': 0.0003176833633643913}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:20,873] Trial 25 finished with value: 1033.18000785241 and parameters: {'alpha': 0.0002357710072866361, 'l1_ratio': 0.38876919478638616, 'max_iter': 50000, 'tol': 0.00038934531148917}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:20,915] Trial 26 finished with value: 1032.1986496615839 and parameters: {'alpha': 1.0321694573594125e-05, 'l1_ratio': 0.6438213784070337, 'max_iter': 40000, 'tol': 0.0006182361547769498}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:21,061] Trial 27 finished with value: 1031.6942416374607 and parameters: {'alpha': 4.130028200415547e-05, 'l1_ratio': 0.8139937055778315, 'max_iter': 45000, 'tol': 0.0002051765361791101}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:21,103] Trial 28 finished with value: 1033.373994652487 and parameters: {'alpha': 0.0002065704093529476, 'l1_ratio': 0.24747657885864055, 'max_iter': 35000, 'tol': 0.00011809116334268643}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:21,235] Trial 29 finished with value: 1053.6376079270708 and parameters: {'alpha': 0.0020946783868014238, 'l1_ratio': 0.5915176709957256, 'max_iter': 40000, 'tol': 0.00015836433151054317}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:21,369] Trial 30 finished with value: 1081.0192383487215 and parameters: {'alpha': 0.0037073998590532783, 'l1_ratio': 0.5075427178876663, 'max_iter': 50000, 'tol': 6.337711639952183e-05}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:21,512] Trial 31 finished with value: 1032.1255468193244 and parameters: {'alpha': 2.9603519011837798e-05, 'l1_ratio': 0.8683126536166355, 'max_iter': 45000, 'tol': 0.00020065678328111956}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:21,554] Trial 32 finished with value: 1031.6807041091458 and parameters: {'alpha': 6.0064709510117846e-05, 'l1_ratio': 0.7512467107130207, 'max_iter': 45000, 'tol': 0.00022606227275033565}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:21,700] Trial 33 finished with value: 1031.7118689209037 and parameters: {'alpha': 6.797956717092797e-05, 'l1_ratio': 0.7275372626784159, 'max_iter': 50000, 'tol': 0.00046158079267442253}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:21,871] Trial 34 finished with value: 1040.1087076666763 and parameters: {'alpha': 2.4754572567984135e-05, 'l1_ratio': 0.9813130867582934, 'max_iter': 40000, 'tol': 0.0007354685778697234}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:22,018] Trial 35 finished with value: 1034.3574264727042 and parameters: {'alpha': 0.0002540209647723235, 'l1_ratio': 0.18801187736787173, 'max_iter': 45000, 'tol': 0.0003305344357053109}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:22,165] Trial 36 finished with value: 1032.004369326813 and parameters: {'alpha': 7.479559795354851e-05, 'l1_ratio': 0.3032145646695368, 'max_iter': 50000, 'tol': 8.702212187289826e-05}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:22,311] Trial 37 finished with value: 1033.263336184978 and parameters: {'alpha': 2.0704723050360772e-05, 'l1_ratio': 0.8967174298704857, 'max_iter': 45000, 'tol': 0.0001513028329905699}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:22,353] Trial 38 finished with value: 1032.9196012627503 and parameters: {'alpha': 0.0004841317710205613, 'l1_ratio': 0.7359702254423195, 'max_iter': 50000, 'tol': 0.00023980345904032693}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:22,499] Trial 39 finished with value: 1031.8702644023365 and parameters: {'alpha': 6.208828485624023e-05, 'l1_ratio': 0.41056985871264184, 'max_iter': 40000, 'tol': 0.0004827037279773988}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:22,645] Trial 40 finished with value: 1031.691974680155 and parameters: {'alpha': 1.7240997568504938e-05, 'l1_ratio': 0.5497758016930572, 'max_iter': 35000, 'tol': 0.000314646860826581}. Best is trial 12 with value: 1031.6636879279954.
[I 2026-07-07 13:28:22,794] Trial 41 finished with value: 1031.6600679955866 and parameters: {'alpha': 2.188551625711764e-05, 'l1_ratio': 0.4806919890776547, 'max_iter': 25000, 'tol': 0.00033429219032461824}. Best is trial 41 with value: 1031.6600679955866.
[I 2026-07-07 13:28:22,950] Trial 42 finished with value: 1032.273851900978 and parameters: {'alpha': 0.0001497501560558505, 'l1_ratio': 0.4717553121908511, 'max_iter': 20000, 'tol': 0.00034528257674508293}. Best is trial 41 with value: 1031.6600679955866.
[I 2026-07-07 13:28:23,109] Trial 43 finished with value: 1031.6775795945662 and parameters: {'alpha': 2.266983719281554e-05, 'l1_ratio': 0.3579355972755633, 'max_iter': 10000, 'tol': 0.00022696864579673117}. Best is trial 41 with value: 1031.6600679955866.
[I 2026-07-07 13:28:23,261] Trial 44 finished with value: 1402.9024801966455 and parameters: {'alpha': 0.17196734760326476, 'l1_ratio': 0.3466206600663985, 'max_iter': 10000, 'tol': 0.0007083582159710278}. Best is trial 41 with value: 1031.6600679955866.
[I 2026-07-07 13:28:23,422] Trial 45 finished with value: 1032.0490138243747 and parameters: {'alpha': 5.780858492599103e-05, 'l1_ratio': 0.013897558179016889, 'max_iter': 15000, 'tol': 0.00016590532534961763}. Best is trial 41 with value: 1031.6600679955866.
[I 2026-07-07 13:28:23,582] Trial 46 finished with value: 1031.742608251214 and parameters: {'alpha': 2.4758668875750583e-05, 'l1_ratio': 0.11524498434829572, 'max_iter': 30000, 'tol': 0.00012743542125507842}. Best is trial 41 with value: 1031.6600679955866.
[I 2026-07-07 13:28:23,734] Trial 47 finished with value: 1031.9045972483175 and parameters: {'alpha': 0.00011229216181894917, 'l1_ratio': 0.638097498239325, 'max_iter': 25000, 'tol': 0.00046763126872118016}. Best is trial 41 with value: 1031.6600679955866.
[I 2026-07-07 13:28:23,872] Trial 48 finished with value: 1201.1469407072632 and parameters: {'alpha': 0.015618415255431365, 'l1_ratio': 0.17885538720282101, 'max_iter': 15000, 'tol': 0.00020438098225829466}. Best is trial 41 with value: 1031.6600679955866.
[I 2026-07-07 13:28:24,023] Trial 49 finished with value: 1034.68743092574 and parameters: {'alpha': 0.0004773617798001984, 'l1_ratio': 0.5357961964504115, 'max_iter': 25000, 'tol': 0.0002810752979803931}. Best is trial 41 with value: 1031.6600679955866.
[I 2026-07-07 13:28:24,162] Trial 50 finished with value: 1568.7812140581884 and parameters: {'alpha': 5.0608122331271685, 'l1_ratio': 0.273074024262549, 'max_iter': 10000, 'tol': 4.1683653135878695e-05}. Best is trial 41 with value: 1031.6600679955866.
[I 2026-07-07 13:28:24,221] Trial 51 finished with value: 1031.6595832683622 and parameters: {'alpha': 1.736019762490924e-05, 'l1_ratio': 0.3908497719023038, 'max_iter': 20000, 'tol': 0.0002310881840748213}. Best is trial 51 with value: 1031.6595832683622.
[I 2026-07-07 13:28:24,368] Trial 52 finished with value: 1031.6775312013585 and parameters: {'alpha': 2.1632263229918672e-05, 'l1_ratio': 0.32741346307069613, 'max_iter': 20000, 'tol': 0.0002382627653336232}. Best is trial 51 with value: 1031.6595832683622.
[I 2026-07-07 13:28:24,526] Trial 53 finished with value: 1031.6616660492289 and parameters: {'alpha': 1.7977626591028938e-05, 'l1_ratio': 0.33684146267794285, 'max_iter': 20000, 'tol': 0.0003571304381202071}. Best is trial 51 with value: 1031.6595832683622.
[I 2026-07-07 13:28:24,690] Trial 54 finished with value: 1031.829037406421 and parameters: {'alpha': 1.009752173732238e-05, 'l1_ratio': 0.45750932265248445, 'max_iter': 20000, 'tol': 0.0003844486963837023}. Best is trial 51 with value: 1031.6595832683622.
[I 2026-07-07 13:28:24,853] Trial 55 finished with value: 1031.6611458348748 and parameters: {'alpha': 1.7485826127381445e-05, 'l1_ratio': 0.32676755562744625, 'max_iter': 25000, 'tol': 0.00028702058156531525}. Best is trial 51 with value: 1031.6595832683622.
[I 2026-07-07 13:28:25,014] Trial 56 finished with value: 1031.7745347536768 and parameters: {'alpha': 4.106324040752231e-05, 'l1_ratio': 0.380090064176175, 'max_iter': 25000, 'tol': 0.0005359053200598244}. Best is trial 51 with value: 1031.6595832683622.
[I 2026-07-07 13:28:25,178] Trial 57 finished with value: 1031.670511855008 and parameters: {'alpha': 1.74281865875881e-05, 'l1_ratio': 0.22096153669092158, 'max_iter': 30000, 'tol': 1.1238625428458173e-05}. Best is trial 51 with value: 1031.6595832683622.
[I 2026-07-07 13:28:25,337] Trial 58 finished with value: 1032.1451169647023 and parameters: {'alpha': 0.0001119724833331417, 'l1_ratio': 0.4022534857334278, 'max_iter': 20000, 'tol': 0.0002870260436485299}. Best is trial 51 with value: 1031.6595832683622.
[I 2026-07-07 13:28:25,499] Trial 59 finished with value: 1031.8127520949297 and parameters: {'alpha': 1.0025829045914458e-05, 'l1_ratio': 0.43813240332165165, 'max_iter': 25000, 'tol': 0.00039279056643924025}. Best is trial 51 with value: 1031.6595832683622.
[I 2026-07-07 13:28:25,651] Trial 60 finished with value: 1031.6917101789968 and parameters: {'alpha': 3.90118574832396e-05, 'l1_ratio': 0.5829599393192968, 'max_iter': 15000, 'tol': 0.00014648132472201063}. Best is trial 51 with value: 1031.6595832683622.
[I 2026-07-07 13:28:25,811] Trial 61 finished with value: 1031.6749680963471 and parameters: {'alpha': 1.852125744040996e-05, 'l1_ratio': 0.2327767290042998, 'max_iter': 30000, 'tol': 1.4838651769056309e-05}. Best is trial 51 with value: 1031.6595832683622.
[I 2026-07-07 13:28:25,972] Trial 62 finished with value: 1031.65962234289 and parameters: {'alpha': 1.547573692198958e-05, 'l1_ratio': 0.2832076058570199, 'max_iter': 30000, 'tol': 2.4234167100098802e-05}. Best is trial 51 with value: 1031.6595832683622.
[I 2026-07-07 13:28:26,133] Trial 63 finished with value: 1031.6597962558467 and parameters: {'alpha': 1.5272095423792463e-05, 'l1_ratio': 0.26513661468548466, 'max_iter': 25000, 'tol': 2.285290495380832e-05}. Best is trial 51 with value: 1031.6595832683622.
[I 2026-07-07 13:28:26,277] Trial 64 finished with value: 1031.7809063677137 and parameters: {'alpha': 3.536153246778867e-05, 'l1_ratio': 0.25968714941760623, 'max_iter': 25000, 'tol': 2.3932178498013256e-05}. Best is trial 51 with value: 1031.6595832683622.
[I 2026-07-07 13:28:26,437] Trial 65 finished with value: 1031.662281613453 and parameters: {'alpha': 1.3969591266388245e-05, 'l1_ratio': 0.3030207483914655, 'max_iter': 20000, 'tol': 2.919445905582512e-05}. Best is trial 51 with value: 1031.6595832683622.
[I 2026-07-07 13:28:26,596] Trial 66 finished with value: 1031.6594750082627 and parameters: {'alpha': 1.5532055598459572e-05, 'l1_ratio': 0.3091073194905784, 'max_iter': 20000, 'tol': 2.7398150842786024e-05}. Best is trial 66 with value: 1031.6594750082627.
[I 2026-07-07 13:28:26,756] Trial 67 finished with value: 1031.7233477364314 and parameters: {'alpha': 2.947287449746573e-05, 'l1_ratio': 0.3284255681117784, 'max_iter': 25000, 'tol': 1.901957981590136e-05}. Best is trial 66 with value: 1031.6594750082627.
[I 2026-07-07 13:28:26,916] Trial 68 finished with value: 1031.9303275694583 and parameters: {'alpha': 5.0994914600284505e-05, 'l1_ratio': 0.14358566128907999, 'max_iter': 20000, 'tol': 2.8286501088775406e-05}. Best is trial 66 with value: 1031.6594750082627.
[I 2026-07-07 13:28:27,062] Trial 69 finished with value: 1032.18749437154 and parameters: {'alpha': 8.838828034732068e-05, 'l1_ratio': 0.19583690898578437, 'max_iter': 30000, 'tol': 4.218388288185265e-05}. Best is trial 66 with value: 1031.6594750082627.
[I 2026-07-07 13:28:27,225] Trial 70 finished with value: 1031.6651065833792 and parameters: {'alpha': 1.3677738300092796e-05, 'l1_ratio': 0.07267129056941515, 'max_iter': 25000, 'tol': 1.879596361999905e-05}. Best is trial 66 with value: 1031.6594750082627.
[I 2026-07-07 13:28:27,371] Trial 71 finished with value: 1031.660638178311 and parameters: {'alpha': 1.4386389622602943e-05, 'l1_ratio': 0.2982307876522479, 'max_iter': 20000, 'tol': 2.96007543376955e-05}. Best is trial 66 with value: 1031.6594750082627.
[I 2026-07-07 13:28:27,516] Trial 72 finished with value: 1031.728083763272 and parameters: {'alpha': 2.8107358515389184e-05, 'l1_ratio': 0.2773528196334236, 'max_iter': 20000, 'tol': 3.409021969521581e-05}. Best is trial 66 with value: 1031.6594750082627.
[I 2026-07-07 13:28:27,659] Trial 73 finished with value: 1032.7339239693029 and parameters: {'alpha': 0.00017198978058037366, 'l1_ratio': 0.329406882524647, 'max_iter': 20000, 'tol': 5.453999564954652e-05}. Best is trial 66 with value: 1031.6594750082627.
[I 2026-07-07 13:28:27,802] Trial 74 finished with value: 1031.6606603779333 and parameters: {'alpha': 1.5917297123805255e-05, 'l1_ratio': 0.36608458448926684, 'max_iter': 25000, 'tol': 1.6306775258842745e-05}. Best is trial 66 with value: 1031.6594750082627.
[I 2026-07-07 13:28:27,953] Trial 75 finished with value: 1031.7586342543177 and parameters: {'alpha': 1.0027438463094189e-05, 'l1_ratio': 0.3730785072223678, 'max_iter': 30000, 'tol': 1.4347351806138307e-05}. Best is trial 66 with value: 1031.6594750082627.
[I 2026-07-07 13:28:28,100] Trial 76 finished with value: 1031.8730593260614 and parameters: {'alpha': 5.261416149857131e-05, 'l1_ratio': 0.2980897474630071, 'max_iter': 25000, 'tol': 2.0354077807730337e-05}. Best is trial 66 with value: 1031.6594750082627.

In [64]:
best_params = study.best_params
best_value = study.best_value

print(f"\nЛУЧШИЕ ГИПЕРПАРАМЕТРЫ Optuna (по CV):")
print(f"Наилучший гиперпараметр alpha = {best_params['alpha']:.6f}")
print(f"Наилучший гиперпараметр l1_ratio = {best_params['l1_ratio']:.4f}")
print(f"max_iter = {best_params['max_iter']}")
print(f"tol = {best_params['tol']:.6f}")
print(f"Лучший CV RMSE: {best_value:.4f}")

ЛУЧШИЕ ГИПЕРПАРАМЕТРЫ Optuna (по CV):
Наилучший гиперпараметр alpha = 0.000016
Наилучший гиперпараметр l1_ratio = 0.3091
max_iter = 20000
tol = 0.000027
Лучший CV RMSE: 1031.6595

In [65]:
best_model = ElasticNet(alpha=best_params['alpha'], l1_ratio=best_params['l1_ratio'], max_iter=best_params['max_iter'], tol=best_params['tol'], random_state=42)
best_model.fit(X_train_scaled, y_train)

y_train_pred = best_model.predict(X_train_scaled)
y_valid_pred = best_model.predict(X_valid_scaled)
y_test_pred = best_model.predict(X_test_scaled)

train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
valid_rmse = np.sqrt(mean_squared_error(y_valid, y_valid_pred))
test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))

train_r2 = r2_score(y_train, y_train_pred)
valid_r2 = r2_score(y_valid, y_valid_pred)
test_r2 = r2_score(y_test, y_test_pred)

train_mae = mean_absolute_error(y_train, y_train_pred)
valid_mae = mean_absolute_error(y_valid, y_valid_pred)
test_mae = mean_absolute_error(y_test, y_test_pred)

results_df = pd.DataFrame({
    'Выборка': ['Train', 'Valid', 'Test'],
    'RMSE': [train_rmse, valid_rmse, test_rmse],
    'R²': [train_r2, valid_r2, test_r2],
    'MAE': [train_mae, valid_mae, test_mae]
})

print("\n" + results_df.to_string(index=False))

Выборка        RMSE       R²        MAE
  Train 1030.454410 0.585840 708.126881
  Valid 1034.919171 0.578094 710.582288
   Test 1040.113466 0.572768 711.143747

In [66]:
previous_results = {
    'GridSearch': {'RMSE': 1040.096362, 'R2': 0.572782},
    'Optuna (без CV)': {'RMSE': 1040.069396, 'R2': 0.572804},
    'Optuna (с CV)': {'RMSE': test_rmse, 'R2': test_r2}
}

comparison_df = pd.DataFrame({
    'Метод': list(previous_results.keys()),
    'Test RMSE': [previous_results[m]['RMSE'] for m in previous_results],
    'Test R²': [previous_results[m]['R2'] for m in previous_results]
})

print(comparison_df.to_string(index=False))

          Метод   Test RMSE  Test R²
     GridSearch 1040.096362 0.572782
Optuna (без CV) 1040.069396 0.572804
  Optuna (с CV) 1040.113466 0.572768

***Вывод: Результаты метрик отличаются сотыми долями, что показывает что модели работают идентично. Но лучшая будет Optuna c cross-validation.***